### ISSUE TITLE
Some issues with internal APIs

### ISSUE THREAD

**Issue by feihu-stripe** [memcached/memcached#1073]
Hi, I want to report a few issues with mcp.internal(), please let us know what you think and we can discuss further on fixes.

#### Issue
```
ms a 0 T3600

HD
mg a t
HD t-1   <<<<< TTL not stored
``` 
#### Fix
Set `exptime` after flags are parsed, i.e.

`rel_time_t exptime = of.exptime;` 

#### Issue
```
ms a 0    <<<<< Valid command failed

CLIENT_ERROR bad command line format
```

#### Fix
Change token check to the following:

`if (pr->ntokens < 3) {`

## Key dump support
This is more of a feature request to be able to dump keys with mcp.internal()
#### Issue
```
lru_crawler metadump all
CLIENT_ERROR parsing request    <<<<< lru_crawler not supported when running in proxy mode
```

#### Workaround
```
    if (strncmp(c->rcurr, "lru_", 4) == 0) {
        cont = el + 1;
        if ((el - c->rcurr) > 1 && *(el - 1) == '\r') {
            el--;
        }
        *el = '\0';
        process_command_ascii(c, c->rcurr);
    } else {
        proxy_process_command(c, c->rcurr, cont - c->rcurr, PROCESS_NORMAL);
    }
```

**Comment by dormando** [comment]
Thanks!
- TTL issue is new to me.
- I did also find the ms issue nearly a month ago but forgot about it while sick, thanks!
- Due to how the crawler works it's not possible to support it properly with mcp.internal.

Your request asks if internal can dump keys, but then your workaround you shows it running the lru crawler directly via ascii. Those aren't the same things.

I've not been able to explicitly document it yet, but control commands and things like lru crawler are effectively "blocked" in proxy mode for security reasons. You should use an alternate port if you want direct access to those commands.

**Comment by feihu-stripe** [comment]
Thanks for clarification, after some research, I figured what I really meant to ask is that the binding protocol is always proxy regardless of port, so using an alternative port still gives me no access to those commands, that's why I came up with the workaround.

`STAT binding_protocol proxy`

**Comment by dormando** [comment]
`./memcached -o proxy_config=t/proxyunits.lua -l 127.0.0.1:11211,proto[ascii]:127.0.0.1:11212`

`proto[ascii|binary|negotiating|proxy]:ip:port` allows forcing a specific protocol handler on a specific listener.

**Comment by feihu-stripe** [comment]
Ah, perfect.

Tested and it works. 

Thanks

**Comment by dormando** [comment]
gonna re-open this until the other two issues are fixed, sorry :)

**Comment by dormando** [comment]
fixed via some trivial commits pushed to `next`; double checked and added a couple basic tests.

**Comment by feihu-stripe** [comment]
Thank you!
