### ISSUE TITLE
Request for Documentation Clarity: Is the proxy version requirements the requirement of the project to configure the proxy, or the version of the backends?

### ISSUE THREAD

**Issue by SpencerMalone** [memcached/memcached#1171]
Hey, quick Q on the new proxy that is quite unclear from the proxy documentation:

In order to use the proxy, do all the backends need to be version 1.6.23 or newer, or is that only the requirement to be able to configure and run the proxy?

Ex: AWS's managed memcached doesn't support 1.6.23 yet as a server. Can I still use the proxy with backends that aren't at that version yet? Is there a minimum backend server version I should be aware of?

**Comment by dormando** [comment]
@SpencerMalone The version requirement is for the proxy itself (since the code didn't exist before). The newer the better for that (but development should be stabilizing/slowing down).

The proxy can talk to almost any version of memcached as a backend. It might work all the way back to the 1.0 series.

**Comment by SpencerMalone** [comment]
Perfect, thank you!

**Comment by dormando** [comment]
fwiw we're in the middle of working on the proxy documentation. Please let us know immediately if something's not working right or not obvious. I'd love the feedback to help figure areas of focus + understand more real use cases. We also have the discord (linked from memcached.org) for realtime assistance if necessary.

good luck!
