### ISSUE TITLE
Clarify expected behaviour for negative expiration times

### ISSUE THREAD

**Issue by edmorley** [memcached/memcached#142]
I'm trying to find out the expected behaviour when a negative expiry time is sent with a command.

Django seems sure that a negative value passed to the client should mean immediately expire:
https://github.com/django/django/blob/1.9.1/django/core/cache/backends/memcached.py#L50-L53
...and pylibmc's docs hint at expected behaviour, but aren't overly clear:
http://sendapatch.se/projects/pylibmc/misc.html#differences-from-python-memcached

However the protocol docs don't currently mention negative values:
https://github.com/memcached/memcached/blob/6b65e45ae2e06626e5abb6dce6e8d10e1204b830/doc/protocol.txt#L79-L90
https://github.com/memcached/memcached/blob/6b65e45ae2e06626e5abb6dce6e8d10e1204b830/doc/protocol.txt#L163-L168

Searching finds many links to wiki pages that now 404 (and sadly aren't in the Google cache):
https://code.google.com/p/memcached/wiki/NewProgramming#Expiration
http://code.google.com/p/memcached/wiki/NewCommands#Standard_Protocol

It's just that I've found inconsistencies in the behaviour with negative expiration times, depending on whether binary mode is used or not (see https://github.com/lericson/pylibmc/issues/202), and it's not clear to me whether this is a client or server issue -- or even if negative values are just no longer supported when using binary mode.

Many thanks :-)

**Comment by xanview** [comment]
Are there any updated links for expiration? - everything I can find is dead including the links on this page :(

**Comment by edmorley** [comment]
Unfortunately I couldn't find any.
@dormando, @dustin, @trondn, I don't suppose you have any ideas?

Many thanks :-)

**Comment by dustin** [comment]
Expiration time is not signed in the binary protocol.  All ones is special
cased in the original spec in a few places, but negative expiration time
was never a thing that was meant to happen, as it adding expired items to a
cache doesn't seem like a useful operation.

**Comment by edmorley** [comment]
Could we explicitly forbid negative expiry times then? Or at least mention they are not officially supported in the spec?

It's just I'm trying to add binary mode support to Django's pylibmc backend, however they have tests that explicitly check the negative expiry time case, which fail under binary mode. In order to convince the Django maintainers that those tests should be disabled, I would ideally need to be able to point at the spec saying they are not supported.

Many thanks :-)

**Comment by edmorley** [comment]
(I'm happy to open a PR to adjust the spec once we get agreement on the desired behaviour :-))

**Comment by dustin** [comment]
Negative isn't even a concept that can be expressed in binary protocol, so
it can't be allowed.  It's not even clear what someone would even expect by
specifying a cached item is introduced that expired three days ago.  That
sounds like a delete operation, but we already have one of those.

**Comment by edmorley** [comment]
Django says it means "set and immediately expire" (see the OP), however like you, I am not sure how it is useful.

I can open a PR to mention that it must be equal or greater to zero, if that would be accepted?
Should it say that requirement applies just when using the binary protocol, or always?

**Comment by edmorley** [comment]
> I can open a PR to mention that it must be equal or greater to zero, if that would be accepted?
> Should it say that requirement applies just when using the binary protocol, or always?

@dustin, don't suppose you saw these questions? :-)

**Comment by dustin** [comment]
Must have missed it, but I don't think it makes sense to document that an
unsigned int can't be zero.  That's implied.

I think any PR can be reviewed on its basis, but I err on the side of more
concise documentation in general.  e.g., I don't think making it both
impossible to express a negative number and documenting that negative
numbers are allowed adds much value.  Similarly, I don't think describing
*why* storing a value that has already expired provides much value.  It's a
wasteful way to issue a "delete" command.  I don't know what someone would
expect it to do or why they'd expect it to work, or even consider it before
reading about it not being possible in docs.

Also, e.g., malloc(3) doesn't mention what happens if you ask for a
negative amount of memory.  You can't, but if it did, you'd suddenly start
considering what it'd e like to get -4K of RAM and what you might do with
anti-RAM and what sort of interactions you might have when combining RAM
and anti-RAM.

sleep(3) doesn't mention what would happen if you asked it to sleep for -5
minutes.  You can't do that in the API, but if you could, we'd suddenly
have time travel and negative expirations might start to make sense.

To your point, though, you can type in negative numbers in the text
protocol and they can be interpreted as negative values.  If you want to
document that particular thing, you might just suggest it was experimental
functionality that was unfortunately found to not alter previous responses
and should not be used.

@dormando might have wildly different opinions, though.

**Comment by edmorley** [comment]
Thank you for the reply.

> I don't think it makes sense to document that an unsigned int can't be zero. That's implied.

My point was more that the docs don't mention it being an unsigned int at all (see links in the issue description) - if it had, I wouldn't have filed this issue :-) The PR I was proposing would add such a definition.

**Comment by dustin** [comment]
Ah, well implementation wise it certainly is and that was the intention.
If you have a good way to document that consistently, then it does make
sense to do that.

**Comment by dormando** [comment]
First: I've finally fixed the wiki:
https://github.com/memcached/memcached/wiki/Programming
(and etc).

This is a weird situation, which being legacy software, memc is full of. As dustin said in binprot you can't even specify expiration times as negative. However in the ASCII protocol they're treated as time_t's or int32_t's during processing. The actual item stores its expiration time as a `rel_time_t`, which is defined as `typedef unsigned int rel_time_t;`

The ASCII protocol contains the following code and comment:
```
    /* Negative exptimes can underflow and end up immortal. realtime() will
       immediately expire values that are greater than REALTIME_MAXDELTA, but less
       than process_started, so lets aim for that. */
    if (exptime < 0)
        exptime = REALTIME_MAXDELTA + 1;
```

So for ASCII prot it's actually supported to go negative as an immediate expiration. It's probably a really bad idea to change this since it's been sitting documented in the code.

Since it's been there forever I just documented it as is. Updated the wiki pages a bit and put a commit in the 'next' branch: https://github.com/memcached/memcached/commit/e7d4521cd8b27f7ebc6e4c1b9aee9eb3544f6af5

going to close this out on a speculation of it this comment being useful. If not just comment and I'll reopen.

**Comment by edmorley** [comment]
Thank you for the confirmation & changes to wiki/protocol.txt.
I'm presuming there isn't a binary protocol equivalent of protocol.txt? (And as such, the wiki is the authoritative documentation for the binary protocol?)

**Comment by dormando** [comment]
it's called protocol-binary.xml and lives in the same directory as protocol.txt :) There's a rendered copy of it on the wiki. If you install xml2rfc and xsltproc `make` will build protocol-binary.txt files.
