### ISSUE TITLE
Items expired by flush_all aren't showed as expired in stats

### ISSUE THREAD

**Issue by shapirus** [memcached/memcached#144]
Demonstration:

```
stats
...
STAT expired_unfetched 0
STAT curr_items 0
```

```
set test 0 0 4
test
STORED
```

```
stats
...
STAT expired_unfetched 0
STAT curr_items 1
```

```
flush_all
OK
```

```
stats
...
STAT expired_unfetched 0
STAT curr_items 1
```

I'd expect the item to show as "expired_unfetched" in this case. Flush_all works, because if I try now to get the item, then it's not returned.

**Comment by dormando** [comment]
Hmmmm.... I'm not sure that showing them as expired_unfetched is correct. Items affected by flush_all aren't tracked super closely. If the storage system runs across them it will count them as "reclaimed" memory, but if fetched it simply doesn't return the object. "expired_unfetched" pretty strictly means that the item reached the end of its stated TTL before being used. Since flush_all is a deliberate action it would kill the meaning of expired_unfetched to mix all of those items in there.

I think the correct thing to do is count them as reclaimed memory from GET's but there isn't a way of doing that in the GET path. :(

I'll leave this issue open a bit longer in case I come up with an easy way of tracking it.

**Comment by dormando** [comment]
Leaving another note: Looks like the LRU crawler isn't differentiating flushed items, and is ticking the expired_unfetched value universally. It uses a unique stat of "crawler_reclaimed" if it does reclaim the memory.

A change went into 1.4.26 which added "get_expired" to the main get routine. that covers some, but there's still no stat for fetching a flushed item.

My current thought is to add a "get_flushed" stat to the fetch routine, and fix the LRU crawler to not tick expired_unfetched if the item is flushed. The crawler_reclaimed stat is still fine as is. It's not worth splitting it into expired/flushed stats.

**Comment by dormando** [comment]
https://github.com/memcached/memcached/commit/80ce01080d1fa1a6e7205c5025fb1c39e5110751

this adds a get_flushed counter, and fixes what I said about the LRU crawler ticking expired_unfetched too much. pushed to `next` branch, will be in next release. closing this out.
