### ISSUE TITLE
a lot of hv parameter in fact take no sense

### ISSUE THREAD

**Issue by taozhijiang** [memcached/memcached#179]
do_item_link(item, hv);
do_item_unlink(item, hv);
do_item_unlink_nolock(item, hv);
assoc_delete(ITEM_key(it), it->nkey, hv);

and other functions so on, the hv parameter are not actually used, even in low-level 
assoc_insert(it, hv); the hv can also been calculated by param it!

**Comment by dormando** [comment]
It does make sense.

Lets trace do_item_link(item, hv):

```
int do_item_link(item *it, const uint32_t hv) {
[...]
    /* Allocate a new CAS ID on link. */
    ITEM_set_cas(it, (settings.use_cas) ? get_cas_id() : 0);
    assoc_insert(it, hv);                              <----------- hv is used here.
    item_link_q(it);
    refcount_incr(&it->refcount);
    item_stats_sizes_add(it);
```

assoc_insert() is in assoc.c:

```
int assoc_insert(item *it, const uint32_t hv) {
[...]
    if (expanding &&
        (oldbucket = (hv & hashmask(hashpower - 1))) >= expand_bucket)
    {
        it->h_next = old_hashtable[oldbucket];
        old_hashtable[oldbucket] = it;
    } else {
        it->h_next = primary_hashtable[hv & hashmask(hashpower)];
        primary_hashtable[hv & hashmask(hashpower)] = it;
    }
```

uses hv quite heavily.

Now, why doesn't assoc_insert() just generat hv from *it?

The answer is to shorten the amount of time spent holding a lock. In this case, an item_lock().

do_store_item() is the only place do_item_link() is effectively called. So what calls do_store_item?

Nothing, really. memcached.c is calling `store_item()`, which calls a wrapper defined in thread.c:

```
/*
 * Stores an item in the cache (high level, obeys set/add/replace semantics)
 */
enum store_item_type store_item(item *item, int comm, conn* c) {
    enum store_item_type ret;
    uint32_t hv;

    hv = hash(ITEM_key(item), item->nkey);
    item_lock(hv);
    ret = do_store_item(item, comm, c, hv);
    item_unlock(hv);
    return ret;
}
```

This wrapper calculates the hash value in order to find and use the correct item lock, which it requests before calling do_store_item.

Passing the hash value down into the function makes total sense at this point, because:

 - You've already calculated it. Saves CPU to not calculate it a second time down in assoc_insert().
 - It is calculated before grabbing any kind of lock, which improves how far you can scale on these locks.

Everything does this in a similar way: Hash outside of the locks when you can, pass the value instead of recalculating.

Hope this explanation is helpful. closing out the issue.

**Comment by taozhijiang** [comment]
hello, dormando

Thanks for your explain in details.
I have traced what you said before. I am concerning is in function assoc_insert, the hv can be fully regenerated from it. What you do for passing the hv param so deep is just avoid the price of call hash func again?

**Comment by dormando** [comment]
That is correct. Avoid recalculating the hv param for performance reasons. It is a very large performance change.
