### ISSUE TITLE
Support for Aliases

### ISSUE THREAD

**Issue by srcspider** [memcached/memcached#182]
*Basic Description: Support for setting an alias to a key, maintained in a separate list to normal keys, which has the property that the alias will never be evicted before the key it points to. Aliases do not affect any of the normal methods, requiring instead specialized alias methods to interact with.*

This solves the problem of the key on retrieval being extremely inconvenient for invalidation. Specifically for cases where cache is local to an entry and namespaces can't be used as an effective strategy for invalidation.

---

**Use Case** (pseudo-code)

```
searched_username = "bob";
cacheKey = "user.entry.username.{searched_username}"
model = mc.get(cacheKey);
if (model == NULL) {
    model = user_model_for_username("bob");
    mc.set(cacheKey, model, time() + Month);
    aliasKey = "user.entry.{model.id}.username"
    mc.setAlias(aliasKey, cacheKey);
    return model;
}
else {
	return model;
}
```

To invalidate the entry with out the `mc.setAlias` line we have to know the field used to generate the key (in the example `username`). This can mean we have to either retrieve the entry or pass the information along to the invalidation routine:

```
cacheKey = "user.entry.username.{username}"
mc.set(cacheKey, NULL, 0);
```

This looks simple but causes problems such as a delete by ID routine being required to retrieve the model to be able to invalidate the cache. On the other hand if we use aliases we can do it like this:

```
aliasKey = "user.entry.{id}.username";
cacheKey = mc.getAlias(aliasKey);
mc.set(cacheKey, NULL, 0);
```
This achieves the same thing but doesn't require any information other then the ID to invalidate any key associated with the model.

In the example I used a routine that searches by username, but it can be extended to something even more complicated such as for example a routine that searches for multiple simultaneous conditions.

The aliases can happily live as an independent system and only really need one property to work:
 - the alias should never be evicted before the key is evicted

In the example I used two calls, but its probably for the best if its simplified to `mc.setWithAlias(aliasKey, cacheKey, model, time() + Month)` for the first routine and `mc.setUsingAlias(aliasKey, NULL, 0)` for the invalidation routine. 

I don't think aliases should be searched when not explicitly asked for. This should also avoid any performance hit for anyone who don't want to use aliases.

**Comment by dormando** [comment]
Thanks for the well written request. This sort of thing isn't very easy though: Mainly that memcached is a distributed system, so in order to actually *find* the key you want to remove your client needs to hash the alias key to the same server that has the final key. OR, the alias gets set where it gets set, and it returns another key that your client needs to re-fetch. Then the problem is that you can't ensure the alias stays as long as the main item without server coordination.

You can work around this a bit by using a tertiary key to do the client hash with, which groups keys to the same servers, but you've just lost the convenience you were trying to gain by aliasing the key in the first place.

There might be room for something like this at some point in the lifespan of this system... however it must be thought of as a distributed system since that is the primary use case. It is also a distributed system without server-to-server coordination, which disallows sharing or syncing tertiary keys like this.

Doing that correctly with a cluster is extremely expensive. Once for performance as a well-synced many-machine cluster will never match the performance of a single independent memcached node. Secondly for manpower as it's extremely difficult to build one of these correctly. You can watch just about every commercial database fail to do this thing correctly: https://aphyr.com/tags/jepsen

I'll leave this open a little longer in case I can noodle any kind of loose compromise.

The one really awful thing that comes to mind would be a client library and a probably little-known feature that was added recently. `-o expirezero_does_not_evict`. If you set this option, keys set with an expiration time of 0 cannot be evicted from the LRU. Storing too many of them will result in OOM errors.

You would implement this by:

 * Taking a key 'foo', alias 'foo-alias'
 * First store 'foo-alias' with an exptime of 0.
 * If OOM error, fail entire write.
 * Store 'foo' if 'foo-alias' succeeds.
 * Bonus points for using CAS controls, 'add', etc.

This has many terrible repercussions:

 * Storing multiple aliases can see network/etc failures.
 * Aliases can go missing if the server they are on is restarted, crashes, or has a network blip.
 * Better keep the alias keys to an absolute minimum size, as they eat into your LRU space.

This _may_ be okay for some people, if:

 * The aliases are used for cache fetches rather than invalidation, since losing an alias causes a miss rather than stale data.
 * TTL's on items are low, or some other reason why occasional invalidation problems aren't the end of the world.
 * If for some reason fetching a key knows (or allows it) to know its aliases, CAS values are used, and a key can be invalidated on fetch if its aliases have gone missing.
 * Most of the above drag down performance with extra roundtrips to the server, alleviated some via multigets?

**Comment by srcspider** [comment]
> Thanks for the well written request. This sort of thing isn't very easy though: Mainly that memcached is a distributed system, so in order to actually find the key you want to remove your client needs to hash the alias key to the same server that has the final key. OR, the alias gets set where it gets set, and it returns another key that your client needs to re-fetch. Then the problem is that you can't ensure the alias stays as long as the main item without server coordination.

Hm.

Would this work?
 
 - mc.setAlias sends the alias key, cache key the alias points to, and a server id (the server id is something the client just generates based on it's own configuration of known servers)
 - if the server for the cacheKey corresponds to the server where the aliasKey is saved then a special noop server id is sent
 - if the server does not recognized the non-noop serverid (which is per client) then the server will negotiate with the client the server details corresponding to the id. On the server the id is then converted to an internal server list id and saved with the new id is saved with the alias (the server caches the client ids to avoid re-negotiation). The server might try to coorce the same server details from multiple clients into a single entry in it's internal list to avoid the follow check...
 - when  the server first negotiates with the client new server details for a given id, it also attempts to connect and set a test key to verify it has api access to the given server; if it fails it sends a message to the client to crash or throw an exception. The severity of the client response to this failure depends on the the method invoked; a combo method that sets the key and alias at the same time can fail more gracefully but a raw `setAlias` method should fail spectacularly to avoid hard to debug errors occurring from cache keys being set in the hope of being invalidated with the alias that just failed to set
 - if the server wishes to evict the alias it reads the server id and if it's the special noop id then it removes the cacheKey from it's key store, otherwise it sends a message to the server in it's server list (populated from talking with the client) corresponding to the id of the aliasKey requesting the other server evict the cacheKey associated with the aliasKey (there's no need for special code for this, since it can be done though normal api)
 - since any time the alias is evicted the cacheKey will be evicted too the constraint on the alias not being evicted before the cache key it points to is indirectly maintained. There's also no requirements of special rules in the eviction logic (other then the requirement for extra communication if the cacheKey is on a different server when an alias is evicted)
 - the server's internal server list is occasionally cleaned of entries that are stale

This system doesn't require a coordinator since the clients are the ones to inform the server of other servers it needs to remember. There should also not be any issue with complicated web like structures between servers and clients since the server list is populated per client. The only complication is that servers need to be able to talk with each other using the same server urls the clients use, which I don't think is a big issue considering this is an optional system. If the server can't ping the 

On a non-distributed use case this is even simpler since the server would always recieve the noop ids.

**Comment by srcspider** [comment]
Small optimization to the method in the previous post: technically so long as memcached has knowledge of the cacheKey's expiration upon creation of the alias (which it has) the alias expiration can be set to be slightly longer then the cacheKey (estimated worst case for server clock mismatch errors). By doing this we can avoid the step of communicating with the server storing the cacheKey if the aliasKey is evicted due to being expired, since the aliasKey is always ahead of the cacheKey we know the cacheKey will be naturally evicted or invalidated on retrieval.

**Comment by dustin** [comment]
Servers talking to servers is pretty much a non-starter.

Have you tried implementing any of your ideas in a client?  It could
actually work there.

**Comment by srcspider** [comment]
> Have you tried implementing any of your ideas in a client?  It could actually work there.

Can't see them being implemented with out effectively just re-creating memcached from scratch with out the distributed over the network caching strategy.

If you're talking bypassing the problem entirely. Already do that, the issue (and it's not a showstopper) is that talking to other servers about changes in the system is annoying when everything can't be simplified to just an ID (or similar). There's just a lot of redundant messaging.

> Servers talking to servers is pretty much a non-starter.

Can you elaborate? 

In the case of the method earlier it should be just one server sending a message to another server; no sophisticated messaging or configuration required since the server with the aliasKey knows exactly which server it needs to send the mesage to (the client told it when sending the aliasKey). 

If the cost is high then I feel like we can also assume that the entire system of two (or however many) servers caching is flawed since there's no way clients can retrieve from them efficiently yet they're prohibitively slow to communicate with each other. The cost of a server sending a message to another server is exactly like the server in question acting like yet another client after all; at most we can say the server with the aliasKey is wasting a bit in using resources that can be used to get connections to talk to the other server.

---

Is there a deep reason why everything has to support memcached-multi-server distributed system? 

I mean I'm sure that works fine if you have machines right next to each other, but don't know if it makes sense to use if you don't know how far apart the machines are or how good the network between them is, or if your cache system needs to be inter-continental.

In those cases it feels like the very idea of caching over the network is prohibitive and its more desirable to have messaging system handle the invalidation. Since any message syncing is decoupled from the requests to the system, so even if it takes longer in extreme cases it's mostly fine since it results in some stale data and not slowdown.

**Comment by srcspider** [comment]
Figured out a better way to do this. You can achieve the same objective of having everything be invalidated by knowing the ID by doing the entire alias strategy backwards and sprinkling a few sanity checks.

**Example**: *Retrieving a user by username* (pseudo-code)
```
usernameHash = crc32(tolower(username));
aliasKey = 'user.entry.username.' + usernameHash;
entryId = mc.get(aliasKey)
if (entryId == null) { // aliasKey cache miss
	
	// retrive from a simple index[1] on username field
	entryId = db_userId_from_username(username)
	cacheKey = 'user.entry.' + entryId

	entry = mc.get(cacheKey)
	if (entry == null) {
		entry = db_user_from_id(entryId);
		mc.set(cacheKey, entry, exp)
	}

	mc.set(aliasKey, entry.id, exp)
	return entry;
}
else { // aliasKey cache hit
	cacheKey = 'user.entry.' + entryId
	entry = mc.get(cacheKey);
	if (entry == null) { // cacheKey cache miss
		entry = db_user_from_id(entryId)
		if (entry.username == username) {
			return entry
		}
		else { // false positive cache hit

			// retrive from a simple index on username field
			entryId = db_userId_by_username(username)
			cacheKey = 'user.entry.' + entryId
			
			entry = mc.get(cacheKey);
			if (entry == null) {
				entry = db_user_from_id(entryId);
				mc.set(cacheKey, entry, exp)
			}

			mc.set(aliasKey, entry.id, exp)
			return entry;
		}
	}
	else { // cacheKey hit
		if (entry.username == username) {
			return entry
		}
		else { // false positive cache hit

			// retrive from a simple index on username field
			entryId = db_userId_by_username(username)
			cacheKey = 'user.entry.' + entryId
			
			entry = mc.get(cacheKey);
			if (entry == null) {
				entry = db_user_from_id(entryId);
				mc.set(cacheKey, entry, exp)
			}

			mc.set(aliasKey, entry.id, exp)
			return entry;
		}
	}
}
```

To invalidate this is sufficient,

```
cacheKey = 'user.entry.' + entryId
mc.set(cacheKey, null, 1);
```

It's not very pretty, but it should work. Although these cases happen often, they don't happen often enough to be that much of a problem. Most languages should also be able to simplify this to a generic call by using function pointers or callbacks of some sort.

**Closing** issue.

---

[1] it should probably use the hash in a hash index, making the call be something like `db_userId_by_usernameHash(usernameHash, username)` where the index on `usernameHash` and `username` would be used for fastest retrieval and anti-collision

**Comment by dormando** [comment]
Looks sane (and would be shorter with sub funcs as you said). Would definitely not use a crc32 (sha1 of some kind), and probably sprinkle adds instead of sets in some places (so parallel processes don't step on each others' keys as much).

To clarify on the other points:

 - It's not that the servers talking to each other is slow because clients talking is slow. It's because the complexity of communications raises with number of servers along with the client request that was already there. What was once a `set` request to a single server, is now potentially several roundtrips between servers (and possibly while the client is waiting!). This is why "eventual consistency" is a whole thing. It loosens the constraints on distributed systems slightly in order to regain some write performance.

 - The typical use case are multiple cache nodes in the same datacenter. I'll revisit this below.

The most basic example is the clastic replicated-cluster expandability conundrum. I have one server which does N reads and Y writes. It's growing and overloaded so now I have two servers doing N*2 reads and Y writes across both. Except N is really the original read capacity (X) minus Y.  (N = X - Y)

As you add servers and add read load, you typically add write load. This slowly lowers you read load until adding new servers isn't cost effective. Thus, sharded replicated pairs/etc.

 - As I linked earlier actually doing a distributed system with proper linearization/etc is extremely difficult. You should give one or two of those jepsen articles a read if you haven't yet; it's generally good to understand these sorts of things.

 - Memcached was written in 2003, where most servers were still 32bit. If you wanted more contiguous cache space,  you had to shard. No-server-chatty cache invalidation was a huge boost in performance and reliability over broadcast based cache.

Since then, servers have gotten a lot larger and companies needing caching have gotten smaller. So much so that many people can't conceptualize why you'd have two servers next to each other.. if you had more than one it would be for geographic redundancy. It turns out memcached just doesn't conceptually scale back down very well. People run one, then get confused when they restart it and have to dump the cache. Then they switch to a key/value database instead.

The entire point of this thing is to go from 1 server to 2 servers, then from 3 onward with the same API and featureset with the maximum amount of scalability. People do message passing like you said, but replicating mutations between entire clusters rather than individual machines.

That's not to say you'd have zero coordination forever, but it might not look like what you expect. IE: https://github.com/golang/groupcache from a few years ago. It trades almost all of memcached's non straight key/value features for some useful coordination features.
