### ISSUE TITLE
Document the supported SASL mechanisms (eg PLAIN, CRAM-MD5)

### ISSUE THREAD

**Issue by edmorley** [memcached/memcached#184]
There are a number of defined SASL mechanisms:
https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer#SASL_mechanisms

I tried looking on the following wiki pages, to see which memcache's binary protocol supported, with no luck:
https://github.com/memcached/memcached/wiki/SASLAuthProtocol
https://github.com/memcached/memcached/wiki/SASLHowto

The following test would imply that the only supported mechanisms are `PLAIN` and `CRAM-MD5`:
https://github.com/memcached/memcached/blob/1.4.29/t/binary-sasl.t#L146

1) Is this correct?
2) Please can this be documented on one (or both) of those wiki pages?
3) Is there any plan to support a TLS based approach? (Given `PLAIN` transfers credentials in plaintext, `CRAM-MD5` can be bruteforced, and neither protect against post-authentication modification of payload.)

Many thanks :-)

**Comment by edmorley** [comment]
Using the Ubuntu 16.04 package (http://packages.ubuntu.com/xenial/memcached ; v1.4.25) and intercepting the methods negotiation, gives me this list:
`DIGEST-MD5 CRAM-MD5 NTLM PLAIN LOGIN ANONYMOUS`

Sadly it seems that most binary protocol compatible clients currently only support `PLAIN` however. For example:
https://github.com/jaysonsantos/python-binary-memcached/blob/d97c5e82796193e8c654dd9d9d867f942fb001ad/bmemcached/protocol.py#L274-L276

**Comment by dormando** [comment]
I haven't directly used the SASL features so it's hard to comment on. From my understanding the methods SASL will offer will depend on the underlying auth system you're connecting memcached to. If you glance at the code it's fairly generic and doesn't specify any particular auth method that I can tell.

(in relation to that test, look at: t/sasl/memcached.conf - you can see it specifying those two mechanisms via the underlying sasl config).

The SASL support has always been weird, because if you don't deeply understand how SASL works there isn't a great way of describing how to use it with memcached. It's probably worth linking to some external documents if a good one can be found.

RE: TLS... while I do know how to write async TLS with OpenSSL (and I guess could offer encryption as well?) it's a fair amount of work and you're the first to ask about it in a long time. I'd be open to a corporate sponsor paying for such a thing but otherwise it'd likely be a ways off. I'm digging out of a rather large backlog.

**Comment by dustin** [comment]
Yes, part of the point of SASL is that the server (or client to some
degree) doesn't actually have to know what it offers or how the mechanisms
work.

The SASL library (and its configuration) has high level APIs for doing
challenges and responses and knowing when things are done (and whether
authentication occurred and by whom).

What dormando said is basically true, except s/with memcached/ -- SASL did
a pretty good job of abstracting auth away so that it could be standardized
and stuff, but you kind of need to understand it to use it.

**Comment by edmorley** [comment]
Ah thank you for the explanation.

To give some more context, my concerns mainly are:
* With a move to cloud based offerings (eg using the Memcachier or Memcached Cloud add-ons on Heroku), more people than in previous years are going to start using memcache not behind VPNs, and in many cases it's not possible to set up a VPC (eg when using Heroku's common runtime)
* To a user that is say used to other protocols with auth/TLS baked in, it's easy to not realise that using memcache binary protocol with SASL auth is still (a) sending the credentials over plaintext (or close to plaintext in the case of easily brute-forceable digest methods), (b) sending the rest of the traffic after authentication over plaintext too.
* That the whole stunnel client+server side solution is a bit of a pain.

I'm going to start trying to add TLS support to some memcache clients (in a similar vein to what was done [for redis clients](https://redislabs.com/blog/secure-redis-ssl-added-to-redsmin-and-clients)), so that it's at least easier for users to connect to providers (such as Memcachier) who are already [running stunnel server-side](https://github.com/memcachier/docs/blob/master/documentation.md#tls). If that takes off, perhaps native TLS support could be considered server-side too.

In the meantime, it would be great to tweak the wiki docs [1][2], such that:
* they mention that the supported SASL methods are those exposed by the OS and/or link to some SASL docs
* they mention that even with SASL, a VPN or TLS in the form of stunnel still needs to be used, since auth and all other content will be sent over plaintext
(I'd open a PR but I don't think that works for the wiki)

Many thanks :-)

[1] https://github.com/memcached/memcached/wiki/SASLAuthProtocol
[2] https://github.com/memcached/memcached/wiki/SASLHowto

**Comment by edmorley** [comment]
For example this existing wording to me reads as "SASL makes your public cloudy instance safe", which is not correct:

> In order to use memcached in a hostile network (e.g. a cloudy ISP where the infrastructure is shared and you can't control it), you're going to want some kind of way to keep people from messing with your cache servers.
> SASL (as described in RFC2222) is a standard for adding authentication mechanisms to protocols in a way that is protocol independent.

**Comment by dormando** [comment]
hmmm... annoying you can't just open a PR for the wiki. I think you could fork it and then point me at a commit or something?

Or I'll just update it. Sorry for the delay; some life stuff came up and I was buried in feature work. TLS is a little difficult. Not sure I could get a sponsorship for it and it's unclear how many people would use it (as opposed to immediately bitrotting and being a maintenance headache). Hard to prioritize it above the backlog I'm working through :(

I'll deal with the wiki soon.

**Comment by dormando** [comment]
and by "Soon" I apparently meant "in a half a year". Just updated a few places slightly. The main wiki pages already link to wikipedia's explanation of it.

**Comment by edmorley** [comment]
Many thanks! :-)
