### ISSUE TITLE
100% CPU usage in lru crawler thread

### ISSUE THREAD

**Issue by panchenji** [memcached/memcached#192]
![screen shot 2016-08-09 at 5 46 14 pm](https://cloud.githubusercontent.com/assets/685491/17538339/393c85b0-5e59-11e6-88e5-83922dfb7a7d.png)
Recently, we updated our codes to use version 1.4.29 and did some tests on the new features like lru_crawler. But we noticed one thread that is always consuming 100% thread. After some investigation, we found that it is the lru_crawler and the root cause for it is as following: 

In items.c line 1053:

`if (lru_crawler_start(i, 0) > 0) {`

The second param in lru_crawler_start 'remaining' here should be set to 1 instead of 0. Since in item_crawler_thread, the stop condition is crawlers[i].remaining == 1. Since the remaining passed from lru_crawler_start is set to 0, there will be a infinite loop in item_crawler_thread.

`if (search == NULL ||
                (crawlers[i].remaining && --crawlers[i].remaining < 1)) {
                if (settings.verbose > 2)
                    fprintf(stderr, "Nothing left to crawl for %d\n", i);
                crawlers[i].it_flags = 0;
                crawler_count--;
                crawler_unlink_q((item *)&crawlers[i]);
                pthread_mutex_unlock(&lru_locks[i]);
                pthread_mutex_lock(&lru_crawler_stats_lock);
                crawlerstats[CLEAR_LRU(i)].end_time = current_time;
                crawlerstats[CLEAR_LRU(i)].run_complete = true;
                pthread_mutex_unlock(&lru_crawler_stats_lock);
                continue;
            }`

Function do_lru_crawler_start will only do remaining -1 times crawl, which should be pointed out in the comments.

**Comment by dormando** [comment]
Hey,

`remaining == 0` doesn't cause an infinite loop, it makes it walk through the entire cache until it hits the top of the LRU (`search == NULL`), then it stops crawling for that class. If you pass in 1 it would crawl exactly one item from the bottom of each class then stop, which isn't useful.

However, you're in luck! The subject of the last few weeks of hacking has been overhauling this code. I've stumbled across a couple bugs while doing so:

 * One is a memory allocation bug in the new large item support in 1.4.29 (unrelated but notable)
 * Two is that the LRU crawler's default sleep was never being respected, since `crawls_persleep` was never decrementing.

Both should be in a release this week. On top of that, the algorithm for deciding when to crawl would run a little too often and has been tweaked. That should hopefully be out this week, but could be next week as well. The combination of running a little too often and the rate limiter being broken would cause it to pin the thread sometimes if you have a lot of items.

I'll leave this open until a release addresses it. thanks!

**Comment by panchenji** [comment]
I see. But we tested it several times and we definitely see the 100% CPU usage thread every time when turning on the lru crawler feature. Have you ever seen this problem before?

**Comment by dormando** [comment]
How many items were in your cache? If it's large enough and spread across multiple slab classes it can look like it's at 100% all the time... or be very close to it. This is partly because each slab class is "scheduled" for a run independently. So if you have 100m items, 50m in class A and 50m in class B... and the min wait time between runs is 5 seconds, one can finish and then the other restarts. It'll restart a slab class if it thinks it can reclaim 1% of the memory in it as well, so if every minute or so 1% of your items have expired via TTL, it'll keep restarting.

That's fixed in the new code. It can't reschedule any runs until all classes have returned, and in general it waits longer, and the sleep bug is fixed. If you want it to run less aggressively you can simply increase the sleep by a bit.

It's in testing now. Should hopefully be up soon.

**Comment by dormando** [comment]
(also; that entire algorithm was a guess from five years ago. if you use the new code and still don't like it, I'd love to have feedback + some data on it so it can be further tweaked)

**Comment by dormando** [comment]
Oh, and I guess it's also pertinent to ask for your testing methodology?

**Comment by panchenji** [comment]
Besides, we also found that in same slab, the search result is ping-pong between the HOT_LRU and COLD_LRU. Here is some log:

crawler_count:2
LRU id:139, search result: 0x636270 search result->prev:0x637a70
LRU id:11, search result: 0x637a70 search result->prev:0x636270
LRU id:139, search result: 0x636270 search result->prev:0x637a70
LRU id:11, search result: 0x637a70 search result->prev:0x636270
LRU id:139, search result: 0x636270 search result->prev:0x637a70
LRU id:11, search result: 0x637a70 search result->prev:0x636270
LRU id:139, search result: 0x636270 search result->prev:0x637a70
LRU id:11, search result: 0x637a70 search result->prev:0x636270

**Comment by dormando** [comment]
That's normal. It crawls all of the slab classes concurrently, which includes the HOT/WARM/COLD variants.

It does mean if you're hammering inserts really hard it could run a little extra long (as stuff pushes down on HOT). There's an improvement for that also in this branch (LRU juggler can't walk past the crawler anymore).

**Comment by dormando** [comment]
That is weird though. It does look like it is getting the same search result multiple times? I definitely haven't seen that. Can you please share your testing methodology so I can take a closer look?

**Comment by panchenji** [comment]
We're doing memcached version upgrade. So we're only doing shadow testing by shadow the traffic from one prod machine with around 1k set qps and 10k get qps. This issue only happened when we just started memcached. So currently, we plan to disable the first round crawl by setting 1 instead of 0 or respect the settings.lru_crawler_tocrawl in first round crawl.

**Comment by dormando** [comment]
Again, if you do that you'll make it not work at all. The code's a little confusing and is actually used for every round.

Just realized that the work branch is public: https://github.com/Netflix-Skunkworks/memcached/tree/crawler_new

It's been baking in testing since last friday between me and the netflix folks. Pending no more bugs should be released soon. Any chance you could give the branch a shot? I'd really appreciate it. You can see it's seen some significant changes.

**Comment by dormando** [comment]
Hi,

The PR is now open: https://github.com/memcached/memcached/pull/193

Testing is going to extend through the rest of the week, so I'll be putting out a bugfix release today. Is there any way I could beg you to try out this PR this week? :) You're practically the only person to write in asking about it and we've been doing a lot of testing on it this week. I'd be really interested in knowing if this solves or at least improves your situation.

Thank you.

**Comment by panchenji** [comment]
Sorry. I was busy working on other stuff days ago. I'll try to make some time to test the 1.4.30 version to see if the cpu usage issue is fixed. I found another issue recently for 1.4.29 with lru_maintainer in another thread I just posted here: https://github.com/memcached/memcached/issues/195

**Comment by dormando** [comment]
Hey,

You'll want to try 1.4.31 for the CPU issue. That includes the new crawler and was just released. Thanks!

**Comment by dormando** [comment]
Did you have a chance to try it out yet?

**Comment by panchenji** [comment]
I just tested. The issue I met before has disappeared. There is no 100% cpu usage thread when starting memcached with -o modern. Thanks for fixing this issue.

**Comment by dormando** [comment]
Excellent! You can thank Netflix for sponsoring the work on that one as well :)

I'm going to close this out.
