### ISSUE TITLE
Multi delete of cache entries

### ISSUE THREAD

**Issue by kamaljoshi** [memcached/memcached#245]
Hey, will it be possible to implement a multi delete command for memcached similar to the get you have? There are situations where we have to expire multiple cache items at once and looping through the keys and issuing expires adds latency penalty on each of the commands. If we can issue multiple keys for delete together then that latency penalty would be there just once.

If you are short on time but this makes sense to implement in memcached, I can try working on this.

**Comment by dormando** [comment]
multiget's pretty awkward from a protocol POV. That's kind of why we went with a different protocol. You have a few options though:
1) binary protocol can stream any type of command (noreply, with reply, stacked, etc)
2) if you have some control over your client you can just stack the ASCII commands together. error handling is a bit weird though.
3) Same as above, but use the NOREPLY modifier (should be documented in doc/protocol.txt). You could loop through keys normalish-ly but not wait on a response.

Probably not going to do multi-delete (since then we'd need multi-set, multi-incr/etc). that's best fixed by using binprot, and from our end probably revising the binprot to help get more people on it.

**Comment by kamaljoshi** [comment]
Thanks, I will look into using binary protocol. I was using Dalli as the client which seems to have support for it.
