### ISSUE TITLE
Key Escaped in "watch mutations" & "lru_crawler metadump"

### ISSUE THREAD

**Issue by amcrn** [memcached/memcached#247]
Memcached Version: 1.4.34

The key for an entry is being escaped in the output of `watch` and `lru_crawler metadump`, but not in `-vvv`. This inconsistency leads me to believe this is a bug vs. purposeful.

Example: If the key is `hello:world`:

* `watch mutations` outputs `OK
ts=1484958168.804271 gid=1 type=item_store key=hello%3Aworld status=stored cmd=set ttl=0 clsid=1`
* `lru_crawler metadump all` outputs `key=hello%3Aworld exp=-1 la=1484958926 cas=71 fetch=no`

`-vvv` outputs:

```
memcached1    | 36: Client using the ascii protocol
memcached1    | <36 set hello:world 0 0 3
memcached1    | 36: going from conn_parse_cmd to conn_nread
memcached1    | > NOT FOUND hello:world
memcached1    | >36 STORED
```

Expected Result: `watch` & `lru_crawler` output `hello:world` not `hello%3Aworld`.

A minor thing, but figured I'd file an Issue. Let me know if I'm off-base here. Cheers!

**Comment by dormando** [comment]
That's intentional. The key was never escaped in -vvv, but the new logging system has an actual format and is intended to be print-safe (even if keys are not), so it's important that the keys are escaped. Spaces, newlines, etc can be inserted if using the binary protocol.

Eventually the logging from -vvv will be deprecated in favor of the watch logs.

That make sense?

**Comment by amcrn** [comment]
Ah, makes complete sense. Thanks for the explanation (and all of your recent additions to memcached, they're awesome).
