### ISSUE TITLE
compare and get?

### ISSUE THREAD

**Issue by jchip** [memcached/memcached#272]
I have fairly big payloads that I want to cache a small subsets locally also, but would like to check with the server every once in a while in case my local copy is outdated.

To do that, I think something like the gets/cas approach would be nice, like a command `cag` (compare and get).  If there's been no change, I just get back a `NOT_CHANGED` response else I get back the new data with the new `cas unique` id.

Is there someway that can be achieved with a single request using current commands?

**Comment by dormando** [comment]
For what it's worth; these sorts of questions are better suited for the mailing list rather than the bug tracker.

I don't believe there's any way of doing that in a single roundtrip. The binary protocol does listen to CAS with a GET but purposefully ignores it, since CAS is aimed at mutations and this is basically the opposite.

Your best bet is to use a secondary small key that points to the large key + some hash you can compare against. Have to be careful though, if you don't bump the large values often enough they could get LRU'ed.

**Comment by jchip** [comment]
Thanks for the info.  Does adding a `cag` command make sense?  It could return `NOT_FOUND` or `NOT_CHANGED`.  If not, then we can close this issue.

**Comment by dormando** [comment]
That would be difficult right now... I'll definitely consider it if we can find a way to rev the protocol at some point. I'll leave this open a little longer and check the code to see if it would be difficult to write or confusing to users.

**Comment by dormando** [comment]
going to close this out for now.. I have a pretty big backlog of work before we can start revving the protocol again :(
