### ISSUE TITLE
memcached-tool script always shows slabs as full.

### ISSUE THREAD

**Issue by webbj74** [memcached/memcached#287]
Since v1.4.14 the `slab stats` statistic `free_chunks_end` [always returns zero](https://github.com/memcached/memcached/commit/423b9fd4b51055eba2f6b6a374def446057308b6#diff-e5e70466a664bf933a9838c582cb6a86R365).

memcached-tool hasn't caught up to this change, however, and now [always shows a slab as full](https://github.com/memcached/memcached/blob/1.4.34/scripts/memcached-tool#L217).

**Comment by dormando** [comment]
good catch, will patch when I get a chance (or anyone else is free to submit a PR!)

**Comment by elfchief** [comment]
I guess the question is ... what classifies as "full"?  free_chunks == 0? Or does this column really make sense at this point?

**Comment by pat-patterson-acq** [comment]
I know that we use that column to quickly diagnose when memcached is full - and yes, when there are no more free chunks, it should read 0 - at the very least, the column should be removed because at a quick glance it's misleading and can lead to a misdiagnosis of a problem during a critical situation.  It's a fantastic too - I use it with the Unix "watch" command to see how memcached is filling, every second.

**Comment by dormando** [comment]
1.5.1 is up
