### ISSUE TITLE
Basic development environment

### ISSUE THREAD

**Issue by neerolyte** [memcached/memcached#292]
It'd be great to have some kind of basic "known good" development environment where if as a newbie to the project I want to verify I've got everything set up "right" before making changes I can expect that the tests pass first time.

I've broken this out of https://github.com/memcached/memcached/issues/265 .

I've put a basic gist up of using Docker with ubuntu/artsy to do this: https://gist.github.com/neerolyte/d62fec59267568c3b9a4936f6f513381

I originally said some tests were failing, but doing a proper `make clean && make && make test` it does actually pass: https://gist.github.com/neerolyte/14d0b6bae1f63ab5c10c5fd360fff1c5

> (bonus points if I can easily set up some kind of buildbot on my own)

Seems like these days it might be easier to just match a docker environment to Travis CI and let Travis build on every commit and rely on the tools in the distro matching "closely enough" to handle this?

I can probably help with that bit if you want e.g send in a PR with Travis config and Dockerfile.

**Comment by dormando** [comment]
Travis is great for webapps but since this is portable I needed a lot of different distros/BSD/32bit/64bit/etc. So I had to stick with buildbots. I have a network of cloudy-VM's that're created when I'm bug-squashing down for a release (as well as an rpi that gets plugged in).

Still, getting another buildbot to validate some docker stuff to help people get going would be good. It also looks like I have a legit build dependency bug since skipping the "make" step after "make clean" isn't building right. I was able to reproduce that.

**Comment by neerolyte** [comment]
They have a couple of distros and even OSes now ([including OS X](https://docs.travis-ci.com/user/multi-os/) :p).

I'm not suggesting to get rid of the buildbot system (I don't know enough about it), just that it might be reasonable to have both configured?

**Comment by neerolyte** [comment]
FWIW I used Travis historically to test a [LXC wrapper](https://github.com/neerolyte/vagueant) before Docker was a thing... so I'm pretty sure I could get a couple of distros running under Docker under Travis (you'll be stuck with the Travis OS though).

**Comment by dormando** [comment]
It's not quite enough :) I've been writing portable software a long time and travis doesn't really do it. I have to worry about kernel versions as well since various features work or don't work and etc. I also really don't want to have to mentally track two different test build environments for a single piece of software.

Also, this is supposed to build directly on OS X since it's occasionally actually used from OS X, so there's nothing pressing on virtualizing the environment. I've said elsewhere though that I've got some bugs to fix in the makefiles/tests (the .c test file should use -debug, not main binary), and can make the build bits more obvious with a README tweak maybe. Directions for setting up docker bits are cool too.

I'll get all this in as soon as I can.

**Comment by oxr463** [comment]
I think this can be closed, since it looks like there is a `docker-compose.yml` file in the repository now.

**Comment by dormando** [comment]
fair enough. I've been chipping at the buildbot setup again too.
