### ISSUE TITLE
[Feature Request] Delete with CAS?

### ISSUE THREAD

**Issue by Haravikk** [memcached/memcached#297]
This proposal is to add a new parameter to `delete`, allowing the passing of a CAS token obtained via `gets`, in which case the `delete` should fail if the CAS token is no longer valid.

I believe this should present no ambiguity in the command, as the only other optional component is `no-reply` which is easily distinguished.

The purpose of this change is to make the `delete` command safer, preventing accidental deletion of a key that is being updated by another process.

This would mean the form of the `delete` command would become:

    delete <key>[ <cas_token>][ no-reply]\r\n

### Example

To give an example, I was recently looking at implementing (very) short term "locking" with memcached. While simplistic implementations use a blind `delete`, this leaves open a possible race condition, so in the end I did the following:

1. Create the "lock" using `add` to ensure it doesn't already exist, retry on failure with a short delay to provide blocking. Value stored can be used to verify ownership.
2. To release the "lock", use `gets` to obtain CAS token, and verify value is still as expected (i.e- we still own the lock).
3. Attempt a `cas` to extend expiration time only if CAS token is still a match (avoids slim chance key expires between `gets` and `delete`).
4. Finally `delete`, since "lock" should now definitely exist, belong to us, and be in no immediate danger of expiry.

Instead of the actual `cas` step I could just do a blind `touch`, then check the value before deleting, but doing this with a CAS token seems more correct, and prevents touching of a lock that no longer belongs to the current process.

Using a delete with CAS however I could combine the final two steps, safe in the knowledge that the `delete` will fail if the lock has expired after retrieving it with `gets`.

Of course I realise memcached isn't really intended for locking like this, and some caveats remain for using it in this way, but I think that a `delete` with CAS is nonetheless a useful addition, and complements the `cas` command itself.

**Comment by dormando** [comment]
The binary protocol already supports this; any chance you could use a binprot-capable client?

**Comment by Haravikk** [comment]
Maybe, but it seems like this feature is still needed for the text protocol then? Why would they be out of sync?

**Comment by dormando** [comment]
delete already has two optional parameters (timeout and noreply), so we'd end up with a new command.

CAS (and a few other things) are just a normal field in binprot, so making it apply to all/most commands is standard. There's no easy way to do that in ASCII.

I've been wanting to ultimately have a text and binary protocol which have parity but there's no real path to doing it without replacing the protocol.. so it's been low priority since it's a lot of work.

**Comment by Haravikk** [comment]
There shouldn't be an issue with `no-reply` being optional, as it's not ambiguous with a CAS token; what's the timeout you mention, is it undocumented? I don't see it in the protocol document?

One alternative to rewriting the protocol would be to have CAS tokens disambiguated in another way, e.g- a leading `@` symbol or such, since it'd be easily distinguished from expiry times etc.

**Comment by dormando** [comment]
it's a timeout parameter, it was deprecated ages ago but we still have to look for it since old clients still send it.

I'm trying to encourage usage of the binprot where possible since ascii as it is has too many weaknesses. I can expand it a bunch and make the parser slower, but that doesn't even fix issues with protocol going out of sync with noreply, lack of optional headers, lack of specified key length, etc.

Having a big old stable protocol with performance expectations is just difficult to deal with. I *am* working my way toward cleaning up the frontend but it requires a big rethink overall. I'm very wary of telling client authors to update clients for a few hacks and then swap out the protocol entirely soon thereafter.

**Comment by dormando** [comment]
I know it seems like a flimsy excuse, but that's basically the deal; it's super hard to change the ascii protocol. It's also mostly just me working on the project so it's taken a very long time for me to get back to working on the frontend.

**Comment by Haravikk** [comment]
No that's perfectly understandable, and it's great that you're working on this at all!

It's actually PHP I'm working with at the moment (unfortunately, but it's paid work at least), but it seems PHP's memcached module doesn't support delete with CAS at all, even with binary protocol enabled, which is why I didn't realise it already existed. I guess that means I'm stuck for now as it doesn't matter what memcached supports, if I want it in PHP I'll have to go out of my way and patch the PHP module but that's a diversion I don't need (but very typical of PHP) 😃

Anyway, since the feature already exists I guess I'll close this. It'd still be nice to see ASCII support but it's not a priority by any means, just nice to have for easy tests via `telnet`.

**Comment by dormando** [comment]
I think pecl/memcached is actively being maintained now. you should try pinging them.
