### ISSUE TITLE
1 Second TTL Expires (Nearly) Immediately

### ISSUE THREAD

**Issue by neoform** [memcached/memcached#307]
When you set the TTL for an item when the clock is nearing the end of that second (eg, 21:00:00.999999) the item expires 0.000001 seconds later instead of 1 second later.

**Comment by dormando** [comment]
Sadly since there's no high resolution clock in use, that's a thing that'll happen. The smallest realistic TTL is 2, and that'll still be +/- 1.

It's always been this way though, and not sure it should be changed. Should I document this better somewhere before closing the issue?

**Comment by neoform** [comment]
I think it could be helpful to others in the future if it was clearly stated somewhere. We've been getting burned by this for over a month and took is quite a while to narrow it down to this issue. We use MC as the locking mechanism in a mutex class on PH (using the ADD command), which in some cases we want them to have a very short TTL, but weren't aware that we'd be losing up to a full second from it. ;)

**Comment by nitrix** [comment]
It could be worth replacing the comparison that's done from `<=` to `<`. It'd effectively make all the keys live a second longer, but also allow for people to use small TTLs (like 1 second) and correctly obtain a least a whole second of liveness. 

In my opinion, it's better to have the keys live possibly a second too long than a second too short. As long as there are no evictions, TTLs should behave like contracts in that manner.

If it stays how it is, then I think it should be documented to avoid other people running into the same issue, yeah (:

**Comment by Moustachauve** [comment]
Maybe a one second TTL should be refused?

**Comment by dormando** [comment]
Sadly, someone somewhere relies on the existing behavior. It's kind of a nightmare to change, and I've already had a lot of bloat with starttime twiddles.

I can document it in doc/protocol.txt, and maybe parts of the wiki, but it's hard to guarantee people will even see that :)

**Comment by neoform** [comment]
It might save someone else a bit of trouble. It took us a pretty long time to narrow it down, since it wasn't really mentioned anywhere online (that we could find). We didn't think that this could be the source of our problem; we figured if this was the case, someone else would have had it happen to them given the maturity of MC.

**Comment by dormando** [comment]
I'm sure some folks have, but few reach out, so thanks :) I'll make sure it's added to any documentation discussing TTL's before closing the issue here.

**Comment by talis2** [comment]
Nitrix suggest to replace =< with < is hands down MOST logical..  it CANNOT affect anyones code (according to dormando "existing behavior" ) .. as timing accuracy is already +/- 1sec.  Thus <  cannot possibly change ANY code except guarantee a 1 sec  TTL (range 1.000001 - 1.999999)  that is still within a +/-1Sec  timeframe  ( 1sec + 1sec = 2 )  plus 1 microsec in worst case.   Neoform team ought not to have experienced that downtime .. (red faces).  May i ask for  links to the "bloat" start-time twiddle  issues ? 

Talks with Mellanox prove one thing .. to offload compute or to bypass kernel in a in-memory store is the only way to gain bandwidth .. Why bog down a distributed access with old protocol ?  if i may quote .. " InfiniBand and RoCE employ lossless link-level flow control, namely, credit-based flow control and Priority Flow Control. Even with unreliable transports (UC/UD), packets are never lost due to buffer overflows.  If i store all my data in DRAM then i have 100% mem-cache hit ,  the only worry is BER ..
Where is CRC to be found in the  request / response headers ?  Is thats the most obvious scary thing missing..? even tho checksum is weak.. is this done on the NIC ? (  IB  does this on a 8 / 10  or  64/66 )
RoCE is great but IB is better .. i cannot find any meta solution to a straightforward all IB (internal) cluster connect.  Lastly, why do i need 300uS latency when i enjoy 3 uS on Infiniband ?  .. may we have some banchmarks, as per  https://hazelcast.com/resources/benchmark-memcached/  .. or compared w/ REDIS

**Comment by dormando** [comment]
It affects code if they set items with a 1s TTL and expect them to be missing some of the time; ie a probabilistic rate limit or lock. Though it's a guess; the truth is anything exposed by an API to the public ends up being used by someone.

I'm not clear on what the rest of your comment is asking about. I've been working with mellanox cards for over a decade and the only thing consistent with them is their production performance is typically 25-50% of what marketing promises. They make a bulk of their sales by undercutting intel on price and aggressively finding customers until someone buys without doing careful tests first (or they don't actually need the performance but enjoy being promised it). I'd take anything they tell you with a grain of salt.

**Comment by talis2** [comment]
Dormando .. the 1s  TTL  is a special case, that can timeout in 1 uS , or
2.621 mS  thus NOT yield any usable timing ..  at  2s  that returns a valid
delay of  1.000001  thru  1.999999 s  so the spec is +0/-0.999999
not +/-1s ..

of course, an individual may opt to change <=  to  <  in his own code. This
cannot affect incoming GETS ?

only can block (drop)  for a 1s TTL setting . in that probabilistic
"Error"  u mention.. 1uS  or  2,621 / 3mS .. and then >5mS may work ( code
function dependent )

**Comment by talis2** [comment]
the above spec may be +0/-1 Sec (did not look at code ; )  BTW , the compute is not RoCE driven (horrible waste of resources, for local cluster in-mem computation)  RoCE is only useful to funnel data from remote server locations (country-wide)  The future looks bright for applications that return statistics on data without moving the data, thus in our situation, as the data is posted (by mobile client App sensors)  we have luxury in a kNN background compute (on cluster DRAM) to selectively pin the results and modify related metadata to assist a public access info-base to return vital stats (8 packets) rather than violin strokin sales brag ..  Is there possibility to add atomic operators to MemCache on a custom kernel call ..  it is that potential i wish to explore .. for linear performance gains on incremental cluster size  8 , 16 , 32 nodes ... have 2 x 16 node avail (tho 8 node with E 26x0 is 128 cores) like to start there, as a practical in-mem data size of 512GB )  its either this or REDIS  ..  there is no other in-memory  to handle >200,000 requests /Sec with atomic ops ?  Maybe AeroSp.  Other MemCache Q's .. i notice expiry as a feature in N seconds ..  When =0 (is all timer overhead disabled for fully persistent data) ? Stop daemon.

i only store data tables : "..you'll still want to have the cache expire occasionally. In case your app has a bug, a crash, a network blip, or some other issue where the cache could become out of sync."  the only blip comes from MemCache .. as in mem leak .. i suppose that is likely with large client number ?

what is its codebase? Can it run LUA , what safeguards needed for ASM ?  Any boolean ops in future ?

Then theres ESI .. the only dynamics i need is for meta-data (as it changes) so ESI is MemCache feature?
All rendering is preset at the client mobile App, only need meta-data (and in some cases data overlays)
There will be no SQL .. the DB only needs structure,  thats provided by external code, it seems, from this

**_Clients are not able to store all types of complex structures. You must turn the data into a pure array, or hash/table type structure before being able to store or retrieve it.  ( Externally ?  how is the Array sorted ..   Pls  links  to  elucidate multi-dimensional storage / GET ..  Link an entire book on the subject.

Since item flags are used when storing the item, the same client is able to know whether or not to deserialize a value before returning it on a 'get'. You don't have to do anything special._**  More ,  pls.


i dont wish this to occur (as common with wrapper offload nightmares) .. (solved by removing handlers)
" These handlers are not removed; therefore memory usage will increase every time a request is received. Not only that, but every time the redis client receives a message, the function function(channel, message) is run. Presumably it doesn't do anything if res has already been sent, but it may be that this would incur a significant overhead if there were many handlers "   Auto removal is best, based on Client inactivity.

Meanwhile, i agree that aggressive marketing needs to be put in a dumpster.  Mell are hypocritic in still selling Connect X2 VPI cards , while dropping all support from WIN OFED 4.9 (not that i wish to run on windows) when X2 VPI are perfectly suited for IB , not SR-IOV (who needs to virtualize a PCIe bottleneck or Server Sync timestamp (only for FOREX traders, who can afford Mlx-6)  ..

https://community.mellanox.com/message/4473#comment-4473

meanwhile RoCE still has its problems ..   who says RoCE is the only RDMA possible?

https://community.mellanox.com/thread/3940

**Comment by dormando** [comment]
That's outside the scope of this project, and this issue. I'll fix the documentation when I get a chance.
