### ISSUE TITLE
Potential buffer overrun vulnerability in function logger_add_watcher(), logger.c file

### ISSUE THREAD

**Issue by shqking** [memcached/memcached#308]
Hi all,
I found one potential buffer overrun vulnerability in function `logger_add_watcher()` at [logger.c#L751](https://github.com/memcached/memcached/blob/master/logger.c#L751).
The vulnerable code is shown as below:
```
enum logger_add_watcher_ret logger_add_watcher(void *c, const int sfd, uint16_t f) {
    ...
    for (x = 0; x < WATCHER_LIMIT; x++) {
        if (watchers[x] == NULL)
            break;
    }
    ...
    watchers[x] = w;
    watcher_count++;
    /* Update what flags the global logs will watch */
    logger_set_flags();

    pthread_mutex_unlock(&logger_stack_lock);
    return LOGGER_ADD_WATCHER_OK;
}
```
`WATCHER_LIMIT` is defined as `20`, and `watchers` is an array with a size of 20 elements.
Assuming that all elements of `watchers` is NOT null, `x` will equal to `20` after the `for`-statement. As a result, the further array-indexing, i.e., `watchers[x] = w`, would lead to buffer overrun.

Thanks,
shqking

**Comment by dormando** [comment]
Hey, thanks for the report!

Right above there is a check for `watcher_count >= WATCHER_LIMIT`. This should prevent the case from happening, but that code could use a refactor for clarity anyway.

If watcher_count == 19, it will find an empty point in the array at an index between 0 and 19. Then the watcher_count is incremented to 20. The next time the loop enters (which is covered by a lock) it will early exit since watcher_count is now == 20, or WATCHER_LIMIT.

I added a `- 1` to the for loop anyway.

**Comment by shqking** [comment]
Yes. This bug would not happen.

Thanks a lot for your explanation.
