### ISSUE TITLE
Potential memory leak vulnerability in function process_bin_stat(), file memcached.c

### ISSUE THREAD

**Issue by shqking** [memcached/memcached#309]
Hi all,
I found a potential memory leak vulnerability in function `process_bin_stat()`, at [memcached.c:L1736](https://github.com/memcached/memcached/blob/master/memcached.c#L1736).
The vulnerable code snippet is shown as below:
```
        if (strncmp(subcmd_pos, " dump", 5) == 0) {
            int len;
            char *dump_buf = stats_prefix_dump(&len);
            if (dump_buf == NULL || len <= 0) {
                out_of_memory(c, "SERVER_ERROR Out of memory generating stats");
                return ;
            } else {
                append_stats("detailed", strlen("detailed"), dump_buf, len, c);
                free(dump_buf);
            }
```
`dump_buf` gets allocated via function `stats_prefix_dump()`.
Assuming that `dump_buf` is NOT null while `len` is not bigger than `0`, the allocated memory `dump_buf` is not freed properly before the function returns, leading to memory leak vulnerability.

Regards,
shqking

**Comment by dormando** [comment]
Thanks for the report!

Fixed in https://github.com/memcached/memcached/commit/c22168bff7b198978525b3bf06d920517c9051a4 - Should make it safer in case of the stats_prefix_dump being modified, but from what I can tell the return state from that function is *either* dump_buf ==  NULL, or len >= 5. So the condition can't trigger in a leak state.

**Comment by shqking** [comment]
Thanks for your reply.

Yes. I agree with you. It is a false positive.
Thanks again.
