### ISSUE TITLE
pointer not initialized before use in do_slabs_newslab()

### ISSUE THREAD

**Issue by pstwo** [memcached/memcached#322]
In do_slabs_newslab(), it is possible for local variable ptr to be used without initialized first if grow_slab_list(id) returns 1.
```
static int do_slabs_newslab(const unsigned int id) {
...
    char *ptr;

    if ((mem_limit && mem_malloced + len > mem_limit && p->slabs > 0
         && g->slabs == 0)) {
        mem_limit_reached = true;
        MEMCACHED_SLABS_SLABCLASS_ALLOCATE_FAILED(id);
        return 0;
    }

    if ((grow_slab_list(id) == 0) ||
        (((ptr = get_page_from_global_pool()) == NULL) &&
        ((ptr = memory_allocate((size_t)len)) == 0))) {

        MEMCACHED_SLABS_SLABCLASS_ALLOCATE_FAILED(id);
        return 0;
    }

    memset(ptr, 0, (size_t)len);
...
```
In that case, the subsequent memset() might get a wrong memory space cleared.

**Comment by dormando** [comment]
Think you're missreading the OR order. grow_slab_list() always returns 1, unless the realloc fails, then it returns early via 0.

That if returns 0 *if* grow_slab_list is 0, OR (the rest of the condition fails). There's no case where grow_slab_list returns 1 and then the other checks return a NULL/0 pointer, since it's checked both times. It's hard to read because of the gross number of ((())) going on though, sorry.

thanks for the report!
