### ISSUE TITLE
Meltdown fix impact on memcached performance

### ISSUE THREAD

**Issue by panchenji** [memcached/memcached#323]
Hi,

We have seen significant performance impact on memcached with meltdown fix.
Does anyone else meet the same problem?

Here is the report for redis performance result:https://gist.github.com/antirez/9e716670f76133ec81cb24036f86ee95

Will try to get a benchmark result later. But not sure if anyone have any temporary solution for it. The version I use is 1.4.29.

**Comment by dormando** [comment]
I won't have time to test it myself until the weekend. Can you specify exactly the impact you're seeing?

There isn't likely to be an easy fix for the slowdown, given that memcached has to run syscalls for reading and writing to the network against most operations. However, since memcached has relatively scalable multithreading, if you have extra CPU available you can increase the number of worker threads for now.

**Comment by dormando** [comment]
ping. could use more details from your end.

**Comment by panchenji** [comment]
We have seen significant impact on soft irq performance, which more likely affects on the network. After set irq affinity to more cores, it seems getting better. Not sure how much it affected on the memcached itself. 

Chenji

**Comment by dormando** [comment]
can you give me a hint as to relative numbers? 5%? 30%? 50%?

**Comment by panchenji** [comment]
I do not have exact percentage for that. I guess it also depends on the use case. But in general we noticed that the interrupts and context switch is slower than before. So for the case that has a high qps with small data was impacted mostly. So far, I just added more capacity to medicate the issue.

**Comment by dormando** [comment]
going to close this; AWS rolled out newer patches which lessen the impact, and there's a development milestone for improving batching syscall rates.
