### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [memcached/memcached#388]
[Extra null pointer checks are not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [a function like “conn_free”](https://github.com/memcached/memcached/blob/91102e15c86c5ed7010670a58f151734a196cc11/memcached.c#L761 "Update candidate").

**Comment by dormando** [comment]
man this makes me nervous.

so this used to be done in Ye Oldene days because some pre-C99 stuff couldn't handle free'ing NULL pointers. I wasn't the one who put these there and I've been on this project for a decade.

Each time I get patches that fix this sort of thing, I think it's great, but almost invariably it screws someone over. That said it's been a while since having to put dummy sizes in blank arrays, etc.

If you can convince me the last device/mainframe/qnx floppy/whatever reason those null checks were created for has been buried in a trash heap somewhere, I'll mark this as "help wanted".

Thanks!

**Comment by elfring** [comment]
I suggest to [take the current POSIX standard into account](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for null before free(p)?") for corresponding software adjustments.
Development tools are available for patching such implementation details.

**Comment by dormando** [comment]
As I said; current isn't my concern, it's "what's in use in the wild". This project tends to get used on crufty old things or odd things: I get patch fixes for AP/UX, HURD, recently lots of bizarre ARM platforms, etc. I tend to not update the code style unless I'm confident, since it's bitten me multiple times so far.

**Comment by elfring** [comment]
How do you think about cooperation with configuration checks like [the macro call "`AC_FUNC_MALLOC`"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Particular-Functions.html "Particular function checks") in [the build specification](https://github.com/memcached/memcached/blob/cf3b8538cf22eb014ae557330ac8720b254c82b5/configure.ac#L10 "Configuration checks")?
Would you like to [reuse wrapper functions](https://stackoverflow.com/questions/262439/create-a-wrapper-function-for-malloc-and-free-in-c "Create a wrapper function for malloc and free in C") under specific circumstances?

**Comment by dormando** [comment]
AC_FUNC_MALLOC doesn't cover free(), and I'm not sure how I'd get the wrapper functions to work if I don't know what platform has trouble and under what situation?

**Comment by dormando** [comment]
Someone could attempt this by adding a configure check for "is free not completely crazy". I'll leave it as help wanted for a while, else will close out since it's harmless.
