### ISSUE TITLE
bad sasl mechanism

### ISSUE THREAD

**Issue by alexalouit** [memcached/memcached#429]
I'm having trouble with memcached and sasl settings,
No matter what I do, the mechanisms list return is not conform to the configuration.

What I do.
```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
..
$ dpkg -l | grep sasl
ii  libsasl2-2:amd64                2.1.25.dfsg1-6+deb7u1             amd64        Cyrus SASL - authentication abstraction library
ii  libsasl2-dev                    2.1.25.dfsg1-6+deb7u1             amd64        Cyrus SASL - development files for authentication abstraction library
ii  libsasl2-modules:amd64          2.1.25.dfsg1-6+deb7u1             amd64        Cyrus SASL - pluggable authentication modules
ii  sasl2-bin                       2.1.25.dfsg1-6+deb7u1             amd64        Cyrus SASL - administration programs for SASL users database
$ cd ~; mkdir sources; cd sources
$ wget http://www.memcached.org/files/memcached-1.5.11.tar.gz
$ tar xzvf memcached-1.5.11.tar.gz
$ cd memcached-1.5.11
$ ./configure --enable-sasl --enable-sasl-pwdb
$ make
$ echo 'mech_list: plain' > /etc/sasl2/memcached_test.conf
$ echo 'user:pass' > /etc/sasl2/memcached_test.sasl
$ export MEMCACHED_SASL_PWDB=/etc/sasl2/memcached_test.sasl; export SASL_CONF_PATH=/etc/sasl2/memcached_test.conf; /root/sources/memcached-1.5.11/memcached -m 32 -u nobody -S -vvvv
```

Memcached load the configuration file, but return another mech list to client.
```
Reading configuration from: </etc/sasl2/memcached_test.conf>
Initialized SASL.
..
authenticated() in cmd 0x21 is true
13: going from conn_parse_cmd to conn_nread
mech:  ``DIGEST-MD5'' with 0 bytes of data
SASL (severity 5): DIGEST-MD5 server step 1
sasl result code:  1
```

Seems to be confirm by dump.
```
$ tcpdump -XX port 11211
..
11:23:35.454567 IP6 memcached.11211 > memcached-client.46574: Flags [P.], seq 1:71, ack 25, win 112, options [nop,nop,TS val 2193114174 ecr 132674868], length 70
	0x0000:  0200 0043 4297 0200 005d e5a6 86dd 6000  ...CB....]....`.
	0x0010:  0000 0066 0640 2001 41d0 000c 0611 0000  ...f.@..A.......
	0x0020:  0000 0000 0102 2001 41d0 000c 0611 0000  ........A.......
	0x0030:  0000 0000 0159 2be6 b5ee 4eb4 16a5 973f  .....Y+...N....?
	0x0040:  1357 8018 0070 f134 0000 0101 080a 82b8  .W...p.4........
	0x0050:  443e 07e8 7534 8120 0000 0000 0000 0000  D>..u4..........
	0x0060:  002e 0002 0000 0000 0000 0000 0000 4449  ..............DI
	0x0070:  4745 5354 2d4d 4435 2043 5241 4d2d 4d44  GEST-MD5.CRAM-MD
	0x0080:  3520 4e54 4c4d 204c 4f47 494e 2050 4c41  5.NTLM.LOGIN.PLA
	0x0090:  494e 2041 4e4f 4e59 4d4f 5553            IN.ANONYMOUS
```

This results in an error because the php client does not support the returned digest-md5 mechanism. (to confirm?)

Did I miss something?

**Comment by omkale** [comment]
Hi @alexalouit 
I am facing the same issue...were you able to get around the problem?

**Comment by alexalouit** [comment]
Hi @omkale,
No, I gave up, I have to try again soon.
May be related with #443?

**Comment by omkale** [comment]
Hey @alexalouit / @dormando ,
Plain text auth works fine. However, when I use DIGEST-MD5, I see that the libmemcached client I am using is not sending the username and password in the memcached AUTH request. See attached packet capture to see the difference:
![memcachedauthrequestplain](https://user-images.githubusercontent.com/14262970/52512218-8f51f280-2bb8-11e9-9761-1d8755de9ee6.png)
![memachedauthrequestmd5](https://user-images.githubusercontent.com/14262970/52512223-911bb600-2bb8-11e9-9e08-0a869b85bcc7.png)

If you check the [Value length :0] for Key: DIGEST-MD5.

Because of this in memcached.c code, under function process_bin_complete_sasl_auth,
nkey = 10
bodylen = 10
vlen = bodylen - nkey = 0
Hence, it prints:mech:  ``DIGEST-MD5'' with 0 bytes of data

I think the question to ask is why libmemcached client is not sending the username, password in its auth request when DIGEST-MD5 is selected.

**Comment by alexalouit** [comment]
I can confirm this is #429 related.
Using directory instead of file for SASL_CONF_PATH works.
