### ISSUE TITLE
_logger_thread_parse_xx: LOGGER_PARSE_SCRATCH is not the length of keybuf

### ISSUE THREAD

**Issue by tnclong** [memcached/memcached#463]
I find the `uriencode(le->key, keybuf, le->nkey, LOGGER_PARSE_SCRATCH);` is strange when studying from your code.

https://github.com/memcached/memcached/blob/master/logger.c#L201

**Comment by dormando** [comment]
LOGGER_PARSE_SCRATCH is big enough to buffer an entire log line, I probably just didn't want to have separate constants for the same buffer.

When URI encoding a key, it's possible to have the resultant line be 3x longer than the real key (250 bytes -> 750), which is why it's not equal to key maxlen either.

**Comment by dormando** [comment]
fixed in 1.5.15
