### ISSUE TITLE
Logfile not created. Ubuntu 18.04

### ISSUE THREAD

**Issue by Dragao75** [memcached/memcached#466]
Hi,

the logfile is never created on a clean Ubuntu 18.04 system. 

I did set the loglevel even to vvv but nothing... 
I have tried creating the file myself and set owner to memcache but still no log..
Installation is done via repository. (apt install memcache) 
I have no clue where to look. See no error in syslog and service is running (as in listening on the port given)

here is my conf
`# memcached default config file
# 2003 - Jay Bonci <jaybonci@debian.org>
# This configuration file is read by the start-memcached script provided as
# part of the Debian GNU/Linux distribution.

# Run memcached as a daemon. This command is implied, and is not needed for the
# daemon to run. See the README.Debian that comes with this package for more
# information.
-d

# Log memcached's output to /var/log/memcached
logfile /var/log/memcached.log

# Be verbose
# -v

# Be even more verbose (print client commands as well)
-vvv

# Start with a cap of 64 megs of memory. It's reasonable, and the daemon default
# Note that the daemon will grow to this size, but does not start out holding this much
# memory
-m 1024

# Default connection port is 11211
-p 11211

# Run the daemon as root. The start-memcached will default to running as root if no
# -u command is present in this config file
-u memcache

# Specify which IP address to listen on. The default is to listen on all IP addresses
# This parameter is one of the only security measures that memcached has, so make sure
# it's listening on a firewalled interface.
-l 127.0.0.1

# Disable UDP
 -U 0

# Limit the number of simultaneous incoming connections. The daemon default is 1024
# -c 1024

# Lock down all paged memory. Consult with the README and homepage before you do this
# -k

# Return error when memory is exhausted (rather than removing items)
# -M

# Maximize core file limit
# -r

# Use a pidfile
-P /var/run/memcached/memcached.pid
`

**Comment by dormando** [comment]
Sorry, I'm not sure. There's no actual logfile in memcached, so the init system would have to redirect it to that file. I'd guess the user doesn't have permissions to create it or something.

You should try the mailing list since more people see it.

**Comment by sahilverma013** [comment]
Hey @Dragao75 ,

I am facing the same issue. Were you able to figure out this.

Thanks!

**Comment by roots-ai** [comment]
+1

**Comment by dormando** [comment]
Alright, I looked into this. The answer is:
`journalctl -u memcached.service` has your logs and will display them. upping the verbosity to -vvv will show them as well.

Please file a bug with ubuntu asking them to update the comments in memcached.conf and/or remove the logfile statement.

Further discussion:

Under 18.04, memcached service is handled via systemd. In previous versions of ubuntu an init script was used, which uses a start script wrapper located in `/usr/share/memcached/scripts/start-memcached`
This wrapper parses the conf file for a "logfile=" entry and redirects STDOUT/STDERR to the file as requested.

Under systemd the wrapper has been replaced with: `/usr/share/memcached/scripts/systemd-memcached-wrapper` which is a cut down version of the original start wrapper. This wrapper completely ignores the logfile entry:
```
# systemd capture stdout by default
my $ignore_directives = ("logfile");
```

... because systemd is god now, I guess.

**Comment by roots-ai** [comment]
Thanks @dormando

**Comment by niranjanthyagaraja** [comment]
I use [https://code.google.com/archive/p/memcache-top/downloads](memcached-top) along with `journalctl -u memcached.service`. Give me a better understanding of whats going on in the server.

**Comment by ndvbd** [comment]
Same problem here. Very annoying.
In the meanwhile I can use: 

journalctl -f -u memcached.service
