### ISSUE TITLE
High CPU usage on memcached server nodes

### ISSUE THREAD

**Issue by aattuluri** [memcached/memcached#487]
This necessarily need not be a memcached issue, but need some pointers in getting to the bottom of the issue.

When we run our memcached cluster (4 nodes) for around a day one or more nodes (random) get into 50% CPU usage and stay there until they are restarted at which point they go to back to normal (2% CPU).

We checked the usage patterns and do not see any correlation to time when the CPU hits 50% and stays there until a restart.

The only suspect we have right now is the number of connections per client. We did see  ~20 connections per client and ~350 connections from one particular client. After a restart it goes back to 2 connections per client.

We are able to reproduce (running for a day or so) on development cluster which means we can add logging/profiling.

Do connections per client have an impact on CPU, if so, how? and 
What's the best way to find out where the CPU cycles are spent in a memcached process?

**Memcached version:**  1.4.4 

@dormando

**Comment by dormando** [comment]
Not much I can do with such an old version. There were a couple bugs along the way that could lead to infinite loops in some worker threads. There's also no point in debugging an ancient version, since I can't exactly patch it :)

Any chance you could try the latest version in your development cluster?

**Comment by aattuluri** [comment]
I think so. We can try the latest version. I will get back to you if we have any issues upgrading.

**Comment by dormando** [comment]
Still having trouble, or can we close this out?

**Comment by aattuluri** [comment]
Wanted to collect more details before getting back to you, but yes, we upgraded to 1.5.14 and still see the same issue. While it could be a client side issue (leaking connections), the server goes into this 50% cpu mode. The only symptom I observe is the number of connections per client go beyond 10 when this occurs. Our client nodes only have 1 connection to memacached server in a normal operating scenario. How can we profile the memcached server CPU or would logging help? If so how should be enable it (would -vv option help?)

PS: While we can take a look at why client connections increase beyond 1 (I suspect connection timeouts etc. resulting in reconnections but not releasing old connections), we need your help to see why memcached server runs hot as a result.

**Comment by dormando** [comment]
So first; I'm guessing it's not 50% CPU, but 100% on one of your two cores? How many CPU cores does the machine have?

If you can (you can share with me privately via e-mail if you want), I need to see the output of `stats` and `stats settings` from your 1.5.14 instance. the 1.4.4 instance has too few statistical counters.

**Comment by aattuluri** [comment]
Yes, its 100% on one core, the machine has 2 cores.
I have sent the stats and stats settings over email.

**Comment by dormando** [comment]
Thanks! So that looks like a spinning deadlock; probably nothing to do with number of connections or what the server's doing, it's just a crash bug of some kind. I know the 1.4.4 series had some like that, but I'm not aware of any in 1.5.14. You noted the stats command doesn't work, as well.

Are you absolutely sure it was running 1.5.14 at the time of the crash loop? Our next step will be getting a gdb backtrace of everything:

```
gdb -p $(pidof memcached)
thread apply all bt
```
Ideally get 2-3 of these snapshots (quit and re-attach GDB, or hit "c", then enter to continue, then control-c to pause it again and grab another back trace.
(only on a hung instance! won't tell me anything on a normal one). This should tell me what everything's locked on and what the spinning thread is doing.

**Comment by aattuluri** [comment]
I will get back to you when I have the backtraces as soon as we see the problem, should take few hours.

**Comment by aattuluri** [comment]
Haven't seen this issue yet, weird, will get back as soon as I see the issue.

**Comment by dormando** [comment]
no worries.

**Comment by aattuluri** [comment]
Ok been running it for more than 24 hrs now and no occurrence. Now I am doubting if we haven't restarted memcached after installing the version on one of the nodes where I saw the problem. Let me get back to you in a couple of days, if we don't see this then we can close out this issue.

**Comment by aattuluri** [comment]
Ok, we updated our production clusters with 1.5.14 and haven't see this issue in last 12+ hours. I will close this now and will update if we see it again.
