### ISSUE TITLE
Even with SASL enabled, will respond to any request over UDP

### ISSUE THREAD

**Issue by bwireman** [memcached/memcached#501]
### Problem

On 1.5.16 and 1.5.13 (So probably all since 1.4.3) a server configured with --enable-sasl-pwdb will respond using the udp/ascii protocol if it is configured to listen on udp. This seems like a really easy way to get around sasl, if a server is mis-configured

**Comment by dormando** [comment]
I noticed this while working on #489 but haven't circled back to it yet; thanks for opening this issue. It's not an issue for the new ascii auth mode, at least. The bug was weird enough that I have to dig to ensure it wasn't intentional (like some overlap where UDP was still supposed to work with SASL), but pretty sure it wasn't. I'll make sure this is fixed for the next release.

**Comment by dormando** [comment]
Ugh overlooked this... fixed in next and will be out in 1.5.20
