### ISSUE TITLE
Add storage command: pop / slice / improved replace

### ISSUE THREAD

**Issue by andrerom** [memcached/memcached#504]
# Context

For a cache library recently added 1-RTT [cache tagging](https://www.google.com/search?q=cache+tagging) adapters for filesystem & Redis.

Current way with Memcached is 2-RTT per cache lookup, with second lookup for tags holding expiry time. And as tag expiry risk being evicted by memcached, it's essentially somewhat broken as tags are less often updated.

Would very much like to do a 1-RTT adapter for Memcached as well, on way would be to take similar approach as Redis using a set. In Memcached as a string that we append to. 

To do that we would need a few features/improvements:
1. *Ideally*: Like 2-RTT approach, need a way to control eviction so we can somehow guarantee tags are not evicted before it's cache
2. *Ideally*: Something like sRem if we care for removing tag relationships on cache updates
3. *Ideally*: A way to avoid hitting cache limits for this data structure too early, for comparison  [limit on Redis is 4 billion members per set](https://redis.io/topics/data-types#sets), in our case we need to be able to do up to millions.
4. And to avoid having to do get + cas for fetching tags on invalidation would need:

# "pop" or "slice" or improved "replace"...\*

Semantic, in one operation:
- empty the value, or maybe more widely useful is to let caller provide a value like '' to replace\* it
- return whole value, or false if not set

_* So might be this can make replace a bit more useful, by somehow telling it to return value if there is one within the same operation instead of true, and allow it to always set the new value even if there were no value from before. But.. naming.._

---

Would this be a set of generic enough features that can make sense in memcached in order to allow e.g. cache tagging? Or do you see other algorithms that would be better for this when it comes to Memcached?

**Comment by dormando** [comment]
The reason why this doesn't presently exist is two fold:

1) vs redis, memcached is fundamentally a distributed system. keys are spread out across all servers in a local pool, so the "tag" and "related keys" would have to first funnel toward a specific server in order to have any related guarantees. The server is designed to work with distributed clients. Clients aren't typically written to cluster keys, though some have specific options (`_by_key` in libmemcached).

2) the internal data structures are simplistic; partly because the simplicity is a feature, and partly because it helps it gets its thread scalability (nearly linear on reads, vs redis being generally single threaded). So there isn't anything internal you can easily work with.

The upside is you don't have a 4 billion key limit, because you can add servers to the cluster :)

Also, unless you've disabled the LRU, tags shouldn't be getting evicted early; they get fetched quite a lot and should be bumped to the top constantly. Have you observed early eviction in reality? It could be a memory balancing issue; with tags being small items vs the rest of the data being large, and older versions of memcached don't balance memory very well. There's one LRU per size-class of items.

I am working on these problems though. Better data structures would be nice.

One improvement, reducing RTT's for some common operations: #484 - this has the semantics of the replace you're talking about (I think?) but a much more complete set of semantics for other patterns. I'm still hacking at it so comments are welcome.

**Comment by andrerom** [comment]
Thanks for sharing, very helpful to get some better insights into the internals :)

> The upside is you don't have a 4 billion key limit, because you can add servers to the cluster :)

That might be the case, but I didn't talk about key limits, but rather value limit _(wen using a "set" datatype)_. In the Redis 1-RTT approach its something like:
```
// Storing cache, and afterwards the tags of the cache item 
$redis->set('entity-44', $value);
$redis->sAdd('tag:type-article', ['entity-44']); // 4 Billion Limit

// Invalidating by tag (one approach, up-to 10k at a time)
$keys = $redis->sPop('tag:type-article', 10000);
$redis->del($keys);
```
From the looks of item memory (default 1mb) limits in Memcached, if cache keys appended has an average length of 20 characters, assuming that is 20 bytes there will in comparison be room for around 50k keys per tag(?).

Also in this approach tags are only touched on invalidation and updates, so in a typical read heavy setup it will become cold and evicted when there is a need to free memory from what I can gather.

> and partly because it helps it gets its thread scalability (nearly linear on reads, vs redis being generally single threaded).
> memcached is fundamentally a distributed system. keys are spread out across all servers in a local pool

These are the reasons I'm eager to have an optimized adapter for Memcached as well :)

> so the "tag" and "related keys" would have to first funnel toward a specific server in order to have any related guarantees

True, I didn't think about that part. But your right, to guarantee not losing tags before cache items, we also need to take into account ending up on same server, in case one of the servers goes down.

> tags shouldn't be getting evicted early; they get fetched quite a lot and should be bumped to the top constantly. 

For the 2-RTT on reads approach this is indeed true, if a cache items is read, the corresponding tag keys are also always read to check the expiry time.

> One improvement, reducing RTT's for some common operations: #484 

I'm not sure I follow that proposal very well. If you look at Redis example above, the "sPOP" is essentially what I'm proposing should be possible in some form here.

**Comment by dormando** [comment]
Ok, I think I understand more now, but not completely. redis sadd/spop are adding values to a set, but it looks like you're annotating tags as surrogate keys. Usually when people talk about this they're doing namespacing:
https://github.com/memcached/memcached/wiki/ProgrammingTricks#namespacing

ie; you're always looking up the secondary key (tag) to find the location of an actual key, which is why there's no "set" limit as keys aren't part of any kind of set and why the tag keys don't get evicted, but it's 2-RTT as you said. Namespacing has an important advantage for invalidation though. In your case you're mass-deleting keys, but namespace invalidation atomically removes the entire set, allowing the old items to fall off the end of the LRU. Even in a distributed case.

Instead it looks like you want to keep lists of keys elsewhere and invalidate them more slowly. Does redis cluster even allow this? I guess it would in your example case, but that's not atomic at all. I'm unsure how generic that can be.

Proper surrogate key invalidation is usually done by associating the items on the backend, so they can be atomically deleted. If you can't atomically invalidate, instead using an spop routine like you said, there's a huge reliance on clients getting it right to use the feature at all; they'd need lock exclusion, and a host of other things... or else again it only works for a narrow use case. Today namespacing is 2-RTT but it works for a wide use case.

The other downside to namespacing is you can't have multiple tags per item. I don't have a good answer for that right now.

Sorry, I don't really have a good answer offhand. If you want multiple tags associate per key and strong semantics you lose coordination-free distribution. We can't really add features that only work with a single server. Will think about it more maybe?

That all said, reading from your initial post I'm still not 100% on how you intended it to work. Some more pseudocode might make it more clear.

**Comment by dormando** [comment]
Anything else you'd like to discuss here? I don't have anything actionable (yet?) so I'll probably close it out soon.

**Comment by dormando** [comment]
Note to self: maybe there's a world where "fetch via other key" is a thing that works, if we ever have a system to keep namespaces in relative sync. Violates the prime directive of not coordinating though :)

**Comment by andrerom** [comment]
Well.. I still don't see a way to do Tags in memcached that both:
- makes sure they are _100% guaranteed_ to not be evicted before their respective cache items
- avoids having to do round trips to memcached per cache item

It could be that I'm missing it from thread above, but doesn't seems like we progressed anywhere on that here.

**Comment by dormando** [comment]
I hadn't seen a further response from you, so it's hard to continue the conversation :)

Memcached is, fundamentally, a zero coordination distributed system. So features that sounds like they'd work great by just adding it to the daemon don't actually work. Keys have to hash to a particular node in a list, and we take it from there.

Basically I do want to see if it's possible to improve this situation since it's a common one, and the PR I linked is me working very hard to reduce a lot of common 2-3x RTT patterns down into 1x RTT. Namespacing is one I haven't talked yet... but I need to hear from users like you about what your workload actually is and what tradeoffs you'd be okay with.

First, it's not clear to me whether you're asking for a surrogate key pattern, a different namespacing pattern, or a more simple single-set pattern. They're all similar but subtly different.

I think my confusion is partly due to this:
```
// Invalidating by tag (one approach, up-to 10k at a time)
$keys = $redis->sPop('tag:type-article', 10000);
$redis->del($keys);
```

You're saying this fetch and delete loop is what you actually do with redis and this is perfectly okay? There's no versioning, no atomicity, etc. There's a huge amount that can go wrong if that's your actual invalidation pattern. It's also a ton more memory since you're storing keys twice (once in the invalidation list, once for the actual key). Is there a different redis feature you were using as well?

**Comment by andrerom** [comment]
> I think my confusion is partly due to this:

The approach in Redis is undergoing changes, and it's better to talk about the highlevel use case here instead of redis specifics as they are indeed not perfect either.

In short it's:
```php
// Retrieval (the part I'm trying to make 1-RTT, aka accomplished in one roundtrip to cache backend)  
$cacheItem = $this->pool->getItem('animal-44');// Same for getItems([...]) for several at once
if ($cacheItem->isHit()) {
    return $cacheItem->get();
}

// Saving 
$cacheItem->set($dog);
$cacheItem->tag(['animal-type-dog', ...]);
$this->pool->save($cacheItem);

// Invalidation on changes to object
$this->pool->deleteItems('animal-44');

// Invalidation on changes to type definition
$this->pool->invalidateTags('animal-type-dog');
```

**Comment by dormando** [comment]
Does redis cluster have this feature at all?

I actually worked for fastly on the varnish team for a long time :) Pretty familiar with their surrogate key impl, which is actually a broadcast invalidation.

**Comment by andrerom** [comment]
> Does redis cluster have this feature at all?

Natively no, but you can accomplish it with for instance Set and it's misc operations.
_Side: Drupal afaik last time I looked does caching in database in order to be able to do this kind of logic for cache invalidation._

**Comment by dormando** [comment]
Memcached isn't going to do anything that redis cluster can't. As I said even if you implement it the same way as varnish, without a broadcast invalidation it won't work. Even with broadcast invalidation you lose atomicity so it limits the use cases pretty severely... but, there're no mc clients that could handle that, and the servers aren't aware of each other to pass it along either.

I think drupal can use some form of DB-backed serialized cache but I'm pretty sure it also has some mc cache plugins.

I understand a lot of users just have one or two memcached's and so it's frustrating to see a lack of features like this... We don't have any features which stop working once you go from one server to a cluster of servers. There's a trusted safety in this, but it does make things inconvenient. Redis is what you get if you take the mc archetype and disregard the clustered aspect, and hey maybe I should've done that back in 2007 :) It seems popular.

You might be able to ham it if we support sets, which might happen soonish. We already have items which exist as chains (chunked items), so the item size limit is actually a gigabyte, it just defaults to a megabyte now. These larger items just chain slab chunks of 512k sizes. It's not a huge stretch to turn this structure into a set you can push and pop against, but is still a lot of work.

**Comment by andrerom** [comment]
Thanks for the explanations.

I definitely don't want you guys to stop prioritizing being able to scale up, we definitely see memcached performing a lot better under heavy load then Redis so wouldn't want that to drop.

So thanks for the update here, I'll keep watching what is coming, and big +1 on efforts like #484 to reduce common roundtrips.

In the meantime we can close this.

**Comment by dormando** [comment]
Just wanted to say that I really appreciate you taking the time to file the issue and discuss the topic. MC is like steering a big slow ship, and despite the popularity we get very little direct feedback as to what users are missing or find important for their workloads.

So every little bit is helpful in figuring out what and how we work on things, even if the question doesn't seem to go anywhere up front. :)
