### ISSUE TITLE
-vv Logging in Memcached doesn't catch "value".

### ISSUE THREAD

**Issue by duclahoang** [memcached/memcached#514]
Hello guys, I'm new here, I've searched for a way to make AOF Log in Memcached.(just like AOF in Redis) to make persistent Memcached or Recovery.
I use "-vv" and "-vvv" option for logging, and the result doesn't have "value".
![Screenshot from 2019-08-01 10-47-31](https://user-images.githubusercontent.com/43582276/62264366-ca3b3180-b449-11e9-8f09-4d6509257cfc.png)
It just has "set key ...." and does not have "value" field.
I have searched for a week but found nothing. Please help me!
Thanks for spending time to read!
(Sorry for my bad English!)

**Comment by dormando** [comment]
There's no way to make an AOF log this way. Also, since memcached is multi-threaded your logs may be written out of order.

What is your use case? Would this work (once finished)? https://github.com/memcached/memcached/pull/342

**Comment by duclahoang** [comment]
Thanks for your reply.
About the use-case, I use AOF log to recover Memcached's status if it crashed. 
I've read #342 , I think it it exactly like what I want, and I don't know how to start with #342, too.
Can you give me a small tutorial about how to use "restartable cache"? or a way to do AOF log ? or what are your opinions on making AOF log ?

**Comment by dormando** [comment]
The #342 feature isn't done yet. When it's done it will have documentation. It won't be crash safe, but you can upgrade memcached, the OS, or gracefully stop and move the memory to a new machine.

It might be possible to build an AOF log based off of the new logger code (logger.c), but it won't be trivial and it's not a priority for me right now, so I wouldn't expect to see it soon.

The restartable cache feature should be done and released within the next month though.

**Comment by duclahoang** [comment]
I'd love to see a new feature. Thanks for your reply. I still have some questions.
It means Memcached itself doesn't have a tool or a feature about AOF at present, right?
Do you think AOF log will be a good feature ?

**Comment by dormando** [comment]
No, there's no way to do it now like I said in my first response. Building from a log means you would have to replay when it restarts, which would severely limit the usage of the feature since replaying could be very slow. Also most users of memcached store ephemeral items which really complicates the idea of an AOF recovery; you have to track time very carefully so you don't accidentally restore expired items, among other problems.

In general this software is a distributed cache, not a database, which means the features look a little different than redis.

that said, if a company is interested enough and willing to pay for development time, I could try to make something work sooner. It would have to meet my specifications as well, since I don't want to support features with limited use or poor scalability/tradeoffs.

**Comment by duclahoang** [comment]
Thank you so much for spending time on my questions ! Maybe I'll find another way to make persistent Memcached. Thanks again ! I'll close the issue right now.
