### ISSUE TITLE
When Extstore start to work?

### ISSUE THREAD

**Issue by duclahoang** [memcached/memcached#517]
Hello guys! Hello dormando, again! 
I want to ask about when Extstore start to work?
At first, I think it will work from begin, but when I make a test with memory limit is 200mb.
I insert data slowly into memcached, all data is written to memory, that means extstore didn't work from begin, right?

After memcached reached memory limit (200mb). It started to write "value" to disk, memory will still increase because of "key,metadata,pointer to value location on disk" and memory will overcome the limit, right? but my htop show me the same RES value(memory doesn't increase)

So I want to know when Extstore start to work? and why RES doesn't increase.
(My use case which I want to work with extstore is save some big record to memcached from beginning)

EDIT 1: I found something about new/old LRU 
new one is included Hot-warm-cold ... 
old one is only cold.
I've read that extstore choose item from the COLD queue. So, I understand why Extstore does not work at beginning

I start to tune lru with "lru mode flat" to turn back to traditional lru (I've read that there is only cold queue in traditional lru) but Extstore still does not work at beginning. Can you give me some guides on this situation?
Thanks for your reading my issue!

**Comment by dormando** [comment]
what is your complete command line for memcached?

some items will end up in COLD no matter what you do, so that shouldn't be the problem. I'm guessing you just need to set "ext_item_age" to a low number then wait for it to flush.

extstore "wants" to use all available memory (200mb in this case) for RAM cache. it doesn't make any sense, normally, to put things to disk unless it would free up space for something else. So by default it waits until memory is mostly full, then starts flushing to disk.

re: RES value. I don't know how you got this impression or why you're looking for it. Extstore uses the same '200mb' memory pool for the small headers that replace the value. So as data writes to extstore it will always use 200mb of memory, but less of that memory will be used to store 'values'. RES won't change.

**Comment by duclahoang** [comment]
At first, I want to say sorry since I reply too late. I had a vacation and I forgot about my issue.
Second, thanks for your reply, I try setting ext_item_age=1 and it works (default value is 4294967295). 
I want to use extstore from the begining because I want to cache some big thing like photo, and I also want to store value to disk as soon as possible.
That's all, I want to say thanks, again.
