### ISSUE TITLE
systemd-memcached-wrapper[931]: Could not open the pid file /var/run/memcached/memcached.pid.tmp for writing: Permission denied

### ISSUE THREAD

**Issue by qy2009** [memcached/memcached#522]
HI, 

I am using OpenLiteSpeed image with memcached. 
when I check memcached ,it got this issue. please see the attached screenshot. 

thanks!

![PastedGraphic-1](https://user-images.githubusercontent.com/51539377/63056489-084e4180-be9d-11e9-95b5-e079b17efa9a.png)
![PastedGraphic-2](https://user-images.githubusercontent.com/51539377/63056494-0ab09b80-be9d-11e9-9ced-0f2afa18195a.png)

**Comment by dormando** [comment]
memcached doesn't have permission to write to /var/run/memcached/ - this isn't really something we can help with. You should talk to the user forums for your OS/distro/vm/docker/whatnot.

**Comment by qy2009** [comment]
I did...OpenLiteSpeed support asked me to contact the developer :(

**Comment by dormando** [comment]
How did you install memcached? What system is that where you're starting it?

**Comment by qy2009** [comment]
the image OpenLiteSpeed installed memcached automatically. it is Ubuntu. 

I noticed the dir permission , it was user memcached, however, the /etc/memcached.conf  
the image has -u www-data.

after I changed the folder permission to www-data. 
it seems the service is running, but the port is not listening...

I tried reboot the server. but same result..and the permission goes back to memcached.

**Comment by dormando** [comment]
I'm really sorry but I don't actually have any control over any of this, nor insight unless I install all the same stuff as you have there and dig into it... which I don't have time for.

This is an installation and package management problem. If you ask around more general user communities folks can help you with the basics of system administration.

The two things that're most likely: 1) as you noted the permissions are mismatched. You seem to be installing it into something and then running a configuration designed for a different package/OS.
2) -l 127.0.0.1 is forcing it to listen on localhost only.  You want it to listen on your local network, since I'm guessing that's some kind of VM or container unless you route the IP block or port your main app won't be able to talk to it no matter what you do.

but I can't really walk you through fixing these things. I don't really use docker myself.

**Comment by qy2009** [comment]
it's ok. thanks so much for getting back to me. 👍
