### ISSUE TITLE
Configure memcached for better performance

### ISSUE THREAD

**Issue by giannisgrigorakos** [memcached/memcached#717]
I would like some help configuring memcached in order to achieve maximum performance.
My system:
Server -> Ubuntu 16.04
Ram -> 8 GB

The reason for asking is because while benchmarking a data set of 1 GB I get a throughput of around 4970 ops/sec in a 50/50 update-read workload with 1 client thread which seem so low.

**Comment by dormando** [comment]
Hey,

Can you please detail your test as much as possible?

Memcached itself can do several hundred thousand operations per second, per worker thread, up to many millions. It's likely the test you did was insufficient or your client is broken.

If you're using "1 client thread" with one socket 4,970 ops/sec would be one op every 0.2ms, which is a reasonable limit for how fast your computer can run syscalls and swap threads. Run more clients/threads or use asynchronous requests: production workloads come from many clients and memcached will scale with them.

**Comment by giannisgrigorakos** [comment]
Sure. I am using YCSB for the benchmarks. I load a workload of 1,000,000 million records. When I execute a benchmark with 1,000,000 operations which are all read operations with one client thread I am getting a very low throughput of around 5000 ops/sec while I was waiting at least 100,000 ops/sec with one thread. As you can see there is a great difference in performance. I also benchmarked redis and with redis I get better results (2x times more) which doesn't make any sense to me.

**Comment by dormando** [comment]
The YCSB clients are implemented differently, which is why there's some disparity there.

If you're configuring it so that the single client is issuing a request, then waiting for a response, then issuing the next request, you will only ever activate a single memcached worker thread and you will be limited by the overhead of switching processes and syscalls.

As I said: 5000 rps with a single client issuing sequential requests is 0.2ms per roundtripped request. Which isn't going to go any lower no matter what you do. If the single client is issuing _batched_ requests: ie streaming requests and streaming the results in, you can easily get 1m rps per client in memcached. I've run parallel read-only benchmarks that have gone in excess of 50 million keys per second. With sets the limit is a lot lower (a few mil, depending).

So either have your client make batches of requests, stream the requests, or use more than a single client.

There's nothing to change in memcached.conf that will overcome an improper benchmark.

**Comment by giannisgrigorakos** [comment]
In my benchmarks I have considered the multithreaded capabilities of
memcached and I run them with 4,8 and 16 client threads to understand how
well memcached scales. As far as i can tell from your benchmarks I must
expect millions of ops/sec for set operations and even more for gets. So in
order to wrap this up, no further configuration is required to get such
results as yours in memcached, right? If so, then the bottleneck of my
benchmarks has to be my YCSB client or the system that I run these tests.
Out of curiosity! Have you ever used YCSB for benchmarking memcached?

**Comment by dormando** [comment]
I have. The default driver is terrible; even if you define multiple YCSB "clients" it pins them through a single tcp socket to memcached, so you only ever engage a single memcached worker thread. This ends up showing GETs topping out at 1m ops/sec and then dropping as you add threads, instead of going up. This has ruined dozens of academic papers. I've been meaning to write a blog post about it for a long time but doing a proper test takes a lot of effort.

For development work on memcached I have mc-crusher: https://github.com/memcached/mc-crusher - which is fast enough to stress the internal datastructures and help me find bottlenecks. I also have: https://github.com/memcached/mctester - which is slower but has more framework for doing complex/realistic production workload tests for more of the algorithmic stuff. The blog posts on memcached.org were written using the mc-crusher tooling.

**Comment by dormando** [comment]
To reiterate though: You want multiple benchmark clients even if memcached is single threaded, because unless you're giving it a constant feed of requests to parse even a single memcached server thread will be 99% idle, waiting for more requests to come in. The threads are event based so each memcached server thread can handle tens of thousands of client TCP sockets.

**Comment by giannisgrigorakos** [comment]
Thank you very much for your time and your clear explanations. I will take a look at the tools that you gave me. This "issue" is ok to close from my side.

**Comment by martin-g** [comment]
@giannisgrigorakos You may check my blog article about benchmarking Memcached on ARM64 here: https://medium.com/@martin.grigorov/compare-memcached-performance-on-x86-64-and-arm64-cpu-architectures-7fe781e34ab8
I use mc-crusher as a test client. I run it regularly and currently it makes around 2.5M GET ops/sec and 850K SET ops/sec.
