### ISSUE TITLE
Confusing meta get behavior after meta delete with invalidate flag

### ISSUE THREAD

**Issue by QuangTung97** [memcached/memcached#851]
**Describe the bug**
`mg` without the `N` flag can still return the `W` flag, after `md` command with the `I` flag. Its a bug or an expected behavior?
If its an expected behaviour, can I disable it?

**To Reproduce**
```
mg key01 v N100
VA 0 W

md key01 I
HD

mg key01 v
VA 0 X W

mg key01 v
VA 0 X Z
```

**System Information**
 - OS/Distro: Docker
 - Version of OS/distro: Docker image memcached:1.6.12
 - Version of memcached: 1.6.12

**Comment by dormando** [comment]
That's intentional (and admittedly a bit weird, but I never received feedback).

`N` is specifically "create a temporary object if it doesn't already exist, with this TTL, and tell me if that happened"
`md key I` is specifically "I'm deliberately setting objects as stale, and the next thing that fetches it has to understand that". Since the object is stale, it seemed important that the fetchers be informed of that (`Z`), but I couldn't decide on if `N` or similar should still be required. I _believe not_ because if `N` is required to get a `W` back that can break some other workflows. ie; if you don't want to autovivify on miss for some reason, but do want to mark objects as stale and revalidate.

Why do you need to disable it? Can you walk me through your expected workflow?

**Comment by QuangTung97** [comment]
Thank you for your answer. I just wonder how long for the next `W` flag to be returned if the `N` flag with `timeout` is not specified?

**Comment by dormando** [comment]
No worries, I appreciate you asking for clarification.

If you as a user want to know how much time is left, add the `t` flag to the gets. The time in W state is the remaining TTL. You can set the TTL remaining with `md`, ie: `md key I T30` - specifically the `T` flag for `md` only works when paired with `I`.

To show again, with metaget:
`mg key v N30 t`

returns the time remaining, creates the item if not exists (with a 30s timeout), and the value if it does exist.

`md key I T30`
... sets the item as stale and to then expire in 30 seconds.
`mg key v t`
... might return a W, also with the TTL so you know how long you have.

You're right in that this can be awkward if you get the `W` without a lot of time remaining. I might be able to improve this in the future, not sure offhand. It might not be too terrible to have `N`'s argument override the TTL on `W`, which I think is what you originally wanted.

**Comment by QuangTung97** [comment]
Thanks for clarification.
So what you said is about this behaviour: `mg N100` does not override the last TTL of  `md key I T30`?
```
ms key 4
ABCD
HD

md key I T30
HD

mg key N100 v t
VA 4 t26 X W
ABCD
```

**Comment by dormando** [comment]
Correct. There's only one TTL value in the object. Sorry for the confusion.
