### ISSUE TITLE
Incorrect error message when using the -l option

### ISSUE THREAD

**Issue by smukil** [memcached/memcached#852]
[Note: This is a minor bug which was misleading me during a dev session]

Memcached can be started with configurable addresses to listen on, using the "-l" option. Eg:
`$> ./memcached -l 127.0.2.1:22122`

If the port `22122` is available, things run smoothly. However, if the port is unavailable, we see the following error message:
`failed to listen on TCP port 11211`

Note that the port number is incorrect and is the default port number `11211` instead of the configured `22122`.

**To Reproduce**
To reproduce, start memcached on the same listen address twice. The second one will repro the error.

**System Information**
Reproducible on any supported Distro.

**Detail (please include!)**
This is because the `server_sockets()` function treats `settings.port` and `settings.inter` differently. If "-l" is provided, `settings.inter` contains the correct port number, whereas `settings.port` the default port, and `settings.port` is used to print the error info, hence printing the incorrect port number.

To fix, track the port information correctly. However, memcached allows listening on multiple interfaces (`./memcached -l <ip1>:<port1>,<ip2>:<port2>`), which means we must print the right conflicting port as part of the error.

**Comment by dormando** [comment]
Nice catch, thanks!

**Comment by smukil** [comment]
@dormando A quick question. When multiple interfaces are provided with the `-l` option, I'm curious why the `server_sockets` code attempts to continue binding with sockets if one of them hits a EADDRINUSE.

https://github.com/memcached/memcached/blob/master/memcached.c#L3702

If any one of them fails, memcached still won't startup as per:
https://github.com/memcached/memcached/blob/master/memcached.c#L6032

Shouldn't `server_sockets` return as soon as it hits the first error?

**Comment by dormando** [comment]
Amazingly I didn't actually write that code so I don't remember. I remember the `server_socket` function itself being tricky and having to actually look through the returned addrinfo structures until one works. EADDRINUSE is specifically exempted while working through the addrinfo structures, which is why the behavior falls through like that. A lot of other errors there do an early return instead.

I don't remember the exact conditions that happens offhand, some ipv6 thing I'm forgetting. You would have to validate/understand exactly why EADDRINUSE is being exempted there before changing the code to bail early.

**Comment by smukil** [comment]
Ok that makes sense. In order to not risk breaking a bunch of cases, I'll leave this code as is while sending in a fix.

The case I was specifically thinking of is when multiple interfaces are provided, and one of them hits an error, the `errno` is reset when binding with the next address, and the caller loses the errno context. I can account for the in the fix though.

**Comment by dormando** [comment]
released in 1.6.14
