### ISSUE TITLE
Meta protocol get (mg) misses (EN) do not return the opaque token (O flag)

### ISSUE THREAD

**Issue by zenbones** [memcached/memcached#880]
I'm attempting to write a memcached client using the meta protocol and non-blocking io. Because the requests are streamed to the server as data is available, and responses are similarly handled, I need to be able to send the right response to its asynchronously waiting request. My plan was to use the opaque token (O flag) to make that connection. I can't just request the key in the response because that's not enough to guarantee the right response connects back with the request that engendered it, but a unique opaque token does work, and can be much shorter. Unfortunately, a cache miss return EN\r\n with *no* flags, and thus ends a perfectly good notion.

Would it be possible to get the opaque token returned with an EN response?
Am I missing some other use of the protocol which would allow asynchronous behavior in the client?

Any advice appreciated

**Comment by dormando** [comment]
Yeah I should've done that. There're a few other commands where the O flag was an open question... So yes; not sure exactly when but soon. There's also an issue that errors won't have opaques necessarily. The original design was something like:
```
mg key Oblah
mg key2 Oblah2
mg key3 Oblah3
mn
```
- Then you read back any responses, matching to opaques, and when you hit mn everything else is a miss. This works for batching but not necessarily streaming as you note. You can throw an `mn` after some small sets of requests and use batch windows if it's more efficient.

I do something similar with streaming arbitrary nonblocking requests to a server. Since it allows non-meta text commands (no opaque at all) I use a request stack and dequeue responses against the stack as they come in. Doesn't allow noreply/quiet modes but otherwise works.

So options depend on how you're tracking the outbound requests. I'll do an audit on meta handlers missing O handling when I get a chance.

**Comment by zenbones** [comment]
The problem with a stack and dequeue is that it presumes that the server is single threaded and that all responses will be strictly ordered. That *may* be true for memcached, but I could not make that assumption.

I did find a workaround, which is to add the N flag to all get requests, which then provides a fully flagged response where I can assume that any W or Z return means that the key was actually a miss. Not sure how efficient this is on the server but memcached is fast and the results are better than not being able to correlate at all.

**Comment by dormando** [comment]
The server is multi-threaded, and yes the responses are all still strictly ordered. Memcached guarantees requests/responses within a single connection are returned in order and always has.

Your workaround is probably fine too.

**Comment by zenbones** [comment]
That's good to know and opens up other options. Thank you.

David Berkman
________________________________

**Comment by zenbones** [comment]
As I have a workaround I'll close this issue and if the opaque tokens get added I can always use them later.
