### ISSUE TITLE
Trying meta set with C0 using a new unseen key returns NF

### ISSUE THREAD

**Issue by zenbones** [memcached/memcached#908]
Against a memcached server on ubuntu 22.04...

> memcached --version
memcached 1.6.14

Sending this command to the server...

[109, 115, 32, 81, 85, 74, 68, 82, 69, 86, 71, 82, 48, 108, 75, 83, 119, 61, 61, 32, 49, 55, 32, 98, 32, 67, 48, 32, 99, 32, 84, 48, 13, 10, -84, -19, 0, 5, 116, 0, 10, 49, 50, 51, 52, 53, 54, 55, 56, 57, 48, 13, 10]

...which should look like this as a string...

ms QUJDREVGR0lKSw== 17 b C0 c T0\r\n
<17 bytes of binary data>\r\n

....returns an NF response.

The key is novel, I stopped and restarted the server before sending the command to make sure. Whereas as this...

ms QUJDREVGR0lKSw== 17 b T0\r\n
<17 bytes of binary data>\r\n

...returns with an HD.

What am I supposed to use as a CAS value for a new item, I assumed it would be 0? Shouldn't the set using C0 return an HD with a non-zero cas value?

David

**Comment by dormando** [comment]
0 had a special meaning that I can't recall offhand.

In the design you're not supposed to blind set a key if you think there's a CAS for it; you fetch first.

Actually I'm forgetting something important... let me just acknowledge that yeah I see this and I'll get back to you in a dayish after I double check. RE: pure CAS usage I mean.

In meta you should be using the token/lease related flags to do this properly (CAS never _really_ could). There're examples in the Meta wiki page. This gives you a completely safe fetch -> miss -> win -> set routine via CAS values and notice flags.

I just want to double check the binprot to make sure the `C0` situation isn't an oversight since I haven't thought about it deeply in a few years.

**Comment by dormando** [comment]
```
   If the Data Version Check (CAS) is nonzero, the requested operation
   MUST only succeed if the item exists and has a CAS value identical to
   the provided value.

   Add MUST fail if the item already exist.

   Replace MUST fail if the item doesn't exist.

   Set should store the data unconditionally if the item exists or not.
```

From the binprot, so translating this to meta means CAS of 0 must be ignored. So I'm pretty sure it's right; you supply a CAS if you have a CAS. In pre-token style a miss requires you submit the "initial" set via `add`, which was some extra round trips that are now optimized out with meta's new options.

If you're trying to blind set but want it to fail if it exists, IIRC `C1` might work but I'd have to double check. Unclear what the use case would be since you won't get the value back in that case, so you wouldn't learn anything useful other than "key exists" and you might as well have sent an `add` anyway.

**Comment by dormando** [comment]
Crap no I confused myself there. C0 was ignored in the binprot case and should be ignored here.

I think I see where it went wrong in the code and what you were trying to do, sorry.

**Comment by dormando** [comment]
Ok coming back one hopefully last time.

If you don't have a cas for meta, you're not supposed to send the `C` flag at all. the little `c` flag will return the new CAS. I'll triple check the code when I get a chance and see if we can just ignore `C0` as a special case. A freshly started server will return a CAS of `0`, so it's currently a valid value. I would have to ensure CAS is seeded as 1 at the same time as making `C0` ignorable.

For client code it would be best to not send `C` unless you have a valid value though. Is that reasonable?

**Comment by dormando** [comment]
Sorry re-pasted a comment that I had deleted earlier, please ignore.

To summarize; there's no functional "set but only if it doesn't already exist with this CAS value".
To reiterate, if you don't already have a CAS value and want to do this, you should use an ADD, like:

```
ms foo 2 c T0 ME
hi
HD c1
ms foo 2 C1 c T0
ho
HD c2
```

This is how binprot worked, as CAS was returned as part of the header. There's also the `N`/etc flags for a more proper method for seeding values. Unfortunately you do need to translate the command a bit based on intent here but I don't think it works otherwise.

**Comment by dormando** [comment]
Nuts.

```
ms foo 2 c T0 ME    
mo
NS c0
```

That looks like a real bug, argh.

**Comment by zenbones** [comment]
Thank you. I think I figured this out and maybe should have said something earlier, but in the client I've been developing I convert a meta set with C0 to a meta add with C1, which, as you note, adds the item only if it doesn't exist and sets the cas to 1 so future cas operations work as expected. Running the implicit conversion saves the end user of the client from special casing every cas get/set loop. In any case, I can close this ticket. Thank you for the clarification. It might be a good addition to the documentation?

**Comment by zenbones** [comment]
Sorry if you found an actual bug but you can open your own ticket on it. But... assuming these follow each other without a server restart between...

```
ms foo 2 c T0 ME
hi
HD c1
ms foo 2 C1 c T0
ho
HD c2

ms foo 2 c T0 ME    
mo
NS c0
mg foo c  
HD c2
```

...not sure I see the bug. The set on key 'foo' to 'ho' succeeds and increments cas to 2. Then the set of key 'foo' to 'mo' fails due to a lack of cas value, and the documentation specifically states that on a failure you can not depend on the cas value returned, so we should ignore the 'c0'. The subsequent get return successful with the current cas value, which is still 2. Looks ok to me?
