### ISSUE TITLE
Jepsen testing

### ISSUE THREAD

**Issue by zamazan4ik** [memcached/memcached#913]
Hi.

During the evaluation of different databases one of the major criteria for us is passing [Jepsen](https://jepsen.io/) test suite. Passing Jepsen test suite confirms some confidence level in testing different quite complicated scenarios in distributed systems.

I did not find any mention of passing Jepsen test suite in the documentation.

My questions are:

- What is the current state of Jepsen tests for the database?
- Do you plan to invest your time into the Jepsen tests? Maybe your current test suite covers all Jepsen cases (or maybe perform even more checks)?
- If the database pass (or not pass) Jepsen test suite, would be awesome if you put this information somewhere into the documentaion. It is really important for the end-users.

Thanks in advance!

**Comment by dormando** [comment]
Hey,

Hopefully I can save you some time; the Jepsen tests aren't relevant to memcached, which is why it's not been tested.

- it's not a database, it's a memory cache. the operations are much simpler and there's no data persistence.
- the distributed nature of the service is in the clients, the servers don't talk to each other. so there's nothing for jepsen to test consistency wise.
- all of the commands are internally atomic, so again there isn't even a sequence of steps jepsen could test.

If it were to be tested I can't imagine how that would even work.

**Comment by zamazan4ik** [comment]
Thanks for the answer! Hm.. I thought that Memcached has some kind of cluster mode. So if it has I guess really there is no huge need to execute Jepsen test suite.

Thank you!

**Comment by dormando** [comment]
It clusters via the clients or a proxy system, they don't talk to each other directly or otherwise provide guarantees for any operations cross-key. You can do any operation atomically to a single key at any time because the clients map keys to single backend servers.

There are plenty of gotchas in production depending on how you handle that, but it's more about which tradeoffs you wish to pick than anything fundamental to the system.
