### ISSUE TITLE
Feature Request: stats in prometheus format

### ISSUE THREAD

**Issue by blkperl** [memcached/memcached#992]
It would be really useful to have the stats metrics available in prometheus format. Currently, admins using prometheus have to use the exporter https://github.com/prometheus/memcached_exporter which adds overhead. PHP recently added support for the fpm status in openmetric format (prometheus) in PHP 8.1 so there is precendent in other large projects for supporting prometheus format. 

Thanks for considering this request and all of the work in maintaining memcached.

**Comment by dormando** [comment]
Ah sorry for not responding sooner. I don't usually like doing things like that, especially since there does seem to be a perfectly good adapter? It looks like they renamed all the stats which I know bothers a lot of people, though I don't understand why it has to be a server. Not very familiar with prometheus guts.

I feel like we try pretty hard to just put the stats out there in a super simple format, and almost everything that consumes stats should have a way of easily importing that.
